#!/usr/bin/env python
# vim:fileencoding=UTF-8:ts=4:sw=4:sta:et:sts=4:ai

__license__   = 'GPL v3'
__copyright__ = '2010, Kovid Goyal <kovid@kovidgoyal.net>'
__docformat__ = 'restructuredtext en'

from functools import partial
from collections import defaultdict

from PyQt4.Qt import (Qt, QLineEdit, QDialog, QGridLayout, QLabel, QCheckBox,
                      QIcon, QDialogButtonBox, QColor, QComboBox, QPushButton)

from calibre.ebooks.metadata.book.base import composite_formatter
from calibre.gui2.dialogs.template_dialog import TemplateDialog
from calibre.gui2.complete import MultiCompleteLineEdit
from calibre.gui2 import error_dialog
from calibre.utils.icu import sort_key

class TemplateLineEditor(QLineEdit):

    '''
    Extend the context menu of a QLineEdit to include more actions.
    '''

    def __init__(self, parent):
        QLineEdit.__init__(self, parent)
        self.tags = None
        self.mi   = None
        self.txt = None

    def set_mi(self, mi):
        self.mi = mi

    def set_db(self, db):
        self.db = db

    def contextMenuEvent(self, event):
        menu = self.createStandardContextMenu()
        menu.addSeparator()

        action_clear_field = menu.addAction(_('Remove any template from the box'))
        action_clear_field.triggered.connect(self.clear_field)
        action_open_editor = menu.addAction(_('Open Template Editor'))
        action_open_editor.triggered.connect(self.open_editor)
        menu.exec_(event.globalPos())

    def clear_field(self):
        self.setText('')
        self.txt = None
        self.setReadOnly(False)
        self.setStyleSheet('TemplateLineEditor { color: black }')

    def open_editor(self):
        if self.txt:
            t = TemplateDialog(self, self.txt, self.mi)
        else:
            t = TemplateDialog(self, self.text(), self.mi)
        t.setWindowTitle(_('Edit template'))
        if t.exec_():
            self.txt = None
            self.setText(t.textbox.toPlainText())

    def enable_wizard_button(self, txt):
        if not txt or txt.startswith('program:\n#tag wizard'):
            return True
        return False

    def setText(self, txt):
        txt = unicode(txt)
        if txt and txt.startswith('program:\n#tag wizard'):
            self.txt = txt
            self.setReadOnly(True)
            QLineEdit.setText(self, '')
            QLineEdit.setText(self, _('Template generated by the wizard'))
            self.setStyleSheet('TemplateLineEditor { color: gray }')
        else:
            QLineEdit.setText(self, txt)

    def tag_wizard(self):
        txt = unicode(self.text())
        if txt and not self.txt:
            error_dialog(self, _('Invalid text'),
                 _('The text in the box was not generated by this wizard'),
                 show=True, show_copy_button=False)
            return
        d = TagWizard(self, self.db, unicode(self.txt), self.mi)
        if d.exec_():
            self.setText(d.template)

    def text(self):
        if self.txt:
            return self.txt
        return QLineEdit.text(self)

class TagWizard(QDialog):

    def __init__(self, parent, db, txt, mi):
        QDialog.__init__(self, parent)
        self.setWindowTitle(_('Coloring Wizard'))
        self.setWindowIcon(QIcon(I('wizard.png')))

        self.mi = mi

        self.columns = []
        self.completion_values = defaultdict(dict)
        for k in db.all_field_keys():
            m = db.metadata_for_field(k)
            if m['datatype'] in ('text', 'enumeration', 'series') and \
                    m['is_category'] and k not in ('identifiers'):
                self.columns.append(k)
                if m['is_custom']:
                    self.completion_values[k]['v'] = db.all_custom(m['label'])
                elif k == 'tags':
                    self.completion_values[k]['v'] = db.all_tags()
                elif k == 'formats':
                    self.completion_values[k]['v'] = db.all_formats()
                else:
                    if k in ('publisher'):
                        ck = k + 's'
                    else:
                        ck = k
                    f = getattr(db, 'all_' + ck, None)
                    if f:
                        if k == 'authors':
                            self.completion_values[k]['v'] = [v[1].\
                                                replace('|', ',') for v in f()]
                        else:
                            self.completion_values[k]['v'] = [v[1] for v in f()]

                if k in self.completion_values:
                    if k == 'authors':
                        self.completion_values[k]['m'] = None
                    else:
                        self.completion_values[k]['m'] = m['is_multiple']

        self.columns.sort(key=sort_key)
        self.columns.insert(0, '')

        l = QGridLayout()
        self.setLayout(l)
        l.setColumnStretch(2, 10)
        l.setColumnMinimumWidth(3, 300)

        h = QLabel(_('And'))
        h.setToolTip('<p>' +
             _('Set this box to indicate that the two conditions must both '
               'be true to return the "color if value found". For example, you '
               'can check if two tags are present, if the book has a tag '
               'and a #read custom column is checked, or if a book has '
               'some tag and has a particular format.'))
        l.addWidget(h, 0, 0, 1, 1)

        h = QLabel(_('Column'))
        h.setAlignment(Qt.AlignCenter)
        l.addWidget(h, 0, 1, 1, 1)

        h = QLabel(_('Not'))
        h.setToolTip('<p>' +
             _('Set this box to indicate that the value must <b>not</b> match '
               'to return the "color if value found". For example, you '
               'can check if a tag does not exist by entering that tag '
               'and checking this box. You can check if tags are empty by '
               'checking this box, entering .* (period asterisk) for the text, '
               'then checking the RE box. The .* regular expression matches '
               'anything, so if this box is checked, it matches nothing. '
               'This box is particularly useful when using the AND box.'))
        h.setAlignment(Qt.AlignCenter)
        l.addWidget(h, 0, 2, 1, 1)

        h = QLabel(_('Values (see the popup help for more information)'))
        h.setAlignment(Qt.AlignCenter)
        h.setToolTip('<p>' +
             _('You can enter more than one value per box, separated by commas. '
               'The comparison ignores letter case. Special note: you can '
               'enter at most one author.<br>'
               'A value can be a regular expression. Check the box to turn '
               'them on. When using regular expressions, note that the wizard '
               'puts anchors (^ and $) around the expression, so you '
               'must ensure your expression matches from the beginning '
               'to the end of the column you are checking.<br>'
               'Regular expression examples:') + '<ul>' +
             _('<li><code><b>.*</b></code> matches anything in the column. No '
               'empty values are checked, so you don\'t need to worry about '
               'empty strings</li>'
               '<li><code><b>A.*</b></code> matches anything beginning with A</li>'
               '<li><code><b>.*mystery.*</b></code> matches anything containing '
               'the word "mystery"</li>') + '</ul></p>')
        l.addWidget(h , 0, 3, 1, 1)

        c = QLabel(_('is RE'))
        c.setToolTip('<p>' +
             _('Check this box if the values box contains regular expressions') + '</p>')
        l.addWidget(c, 0, 4, 1, 1)

        c = QLabel(_('Color if value found'))
        c.setToolTip('<p>' +
             _('At least one of the two color boxes must have a value. Leave '
               'one color box empty if you want the template to use the next '
               'line in this wizard. If both boxes are filled in, the rest of '
               'the lines in this wizard will be ignored.') + '</p>')
        l.addWidget(c, 0, 5, 1, 1)
        c = QLabel(_('Color if value not found'))
        c.setToolTip('<p>' +
             _('This box is usually filled in only on the last test. If it is '
               'filled in before the last test, then the color for value found box '
               'must be empty or all the rest of the tests will be ignored.') + '</p>')
        l.addWidget(c, 0, 6, 1, 1)

        self.andboxes = []
        self.notboxes = []
        self.tagboxes = []
        self.colorboxes = []
        self.nfcolorboxes = []
        self.reboxes = []
        self.colboxes = []
        self.colors = [unicode(s) for s in list(QColor.colorNames())]
        self.colors.insert(0, '')

        maxlines = 10
        for i in range(1, maxlines+1):
            ab = QCheckBox(self)
            self.andboxes.append(ab)
            if i != maxlines:
                # let the last box float in space
                l.addWidget(ab, i, 0, 2, 1)
                ab.stateChanged.connect(partial(self.and_box_changed, line=i-1))
            else:
                ab.setVisible(False)

            w = QComboBox(self)
            w.addItems(self.columns)
            l.addWidget(w, i, 1, 1, 1)
            self.colboxes.append(w)

            nb = QCheckBox(self)
            self.notboxes.append(nb)
            l.addWidget(nb, i, 2, 1, 1)

            tb = MultiCompleteLineEdit(self)
            tb.set_separator(', ')
            self.tagboxes.append(tb)
            l.addWidget(tb, i, 3, 1, 1)
            w.currentIndexChanged[str].connect(partial(self.column_changed, valbox=tb))

            w = QCheckBox(self)
            self.reboxes.append(w)
            l.addWidget(w, i, 4, 1, 1)

            w = QComboBox(self)
            w.addItems(self.colors)
            self.colorboxes.append(w)
            l.addWidget(w, i, 5, 1, 1)

            w = QComboBox(self)
            w.addItems(self.colors)
            self.nfcolorboxes.append(w)
            l.addWidget(w, i, 6, 1, 1)

        if txt:
            lines = txt.split('\n')[3:]
            i = 0
            for line in lines:
                if line.startswith('#'):
                    vals = line[1:].split(':|:')
                    if len(vals) == 2:
                        t, c = vals
                        nc = ''
                        re = False
                        f = 'tags'
                        a = False
                        n = False
                    else:
                        t,c,f,nc,re,a,n = vals
                    try:
                        self.colboxes[i].setCurrentIndex(self.colboxes[i].findText(f))
                        self.colorboxes[i].setCurrentIndex(
                                                self.colorboxes[i].findText(c))
                        self.nfcolorboxes[i].setCurrentIndex(
                                                self.nfcolorboxes[i].findText(nc))
                        self.tagboxes[i].setText(t)
                        self.reboxes[i].setChecked(re == '2')
                        self.andboxes[i].setChecked(a == '2')
                        self.notboxes[i].setChecked(n == '2')
                        i += 1
                    except:
                        pass

        w = QLabel(_('Preview'))
        l.addWidget(w, 99, 1, 1, 1)
        w = self.test_box = QLineEdit(self)
        w.setReadOnly(True)
        l.addWidget(w, 99, 3, 1, 1)
        w = QPushButton(_('Test'))
        l.addWidget(w, 99, 5, 1, 1)
        w.clicked.connect(self.preview)

        bb = QDialogButtonBox(QDialogButtonBox.Ok|QDialogButtonBox.Cancel, parent=self)
        l.addWidget(bb, 100, 3, 1, 2)
        bb.accepted.connect(self.accepted)
        bb.rejected.connect(self.reject)
        self.template = ''

    def preview(self):
        if not self.generate_program():
            return
        t = composite_formatter.safe_format(self.template, self.mi,
                                            _('EXCEPTION'), self.mi)
        self.test_box.setText(t)

    def column_changed(self, s, valbox=None):
        k = unicode(s)
        if k in self.completion_values:
            valbox.update_items_cache(self.completion_values[k]['v'])
            if self.completion_values[k]['m']:
                valbox.set_separator(', ')
            else:
                valbox.set_separator(None)
        else:
            valbox.update_items_cache([])
            valbox.set_separator(None)

    def generate_program(self):
        res = ("program:\n#tag wizard -- do not directly edit\n"
               "  first_non_empty(\n")
        lines = []
        was_and = False
        had_line = False

        line = 0
        for tb, cb, fb, nfcb, reb, ab, nb in zip(
                    self.tagboxes, self.colorboxes, self.colboxes,
                    self.nfcolorboxes, self.reboxes, self.andboxes, self.notboxes):
            f = unicode(fb.currentText())
            if not f:
                continue
            m = self.completion_values[f]['m']
            c = unicode(cb.currentText()).strip()
            nfc = unicode(nfcb.currentText()).strip()
            re = reb.checkState()
            a = ab.checkState()
            n = nb.checkState()
            line += 1

            if n == 2:
                tval = ''
                fval = '1'
            else:
                tval = '1'
                fval = ''

            if m:
                tags = [t.strip() for t in unicode(tb.text()).split(',') if t.strip()]
                if re == 2:
                    tags = '$|^'.join(tags)
                else:
                    tags = ','.join(tags)
            else:
                tags = unicode(tb.text()).strip()
                if f == 'authors':
                    tags.replace(',', '|')

            if (tags or f) and not (tags and f and (a == 2 or c)):
                error_dialog(self, _('Invalid line'),
                             _('Line number {0} is not valid').format(line),
                             show=True, show_copy_button=False)
                return False

            if c not in self.colors:
                error_dialog(self, _('Invalid color'),
                             _('The color {0} is not valid').format(c),
                             show=True, show_copy_button=False)
                return False
            if nfc not in self.colors:
                error_dialog(self, _('Invalid color'),
                             _('The color {0} is not valid').format(nfc),
                             show=True, show_copy_button=False)
                return False

            if not was_and:
                if had_line:
                    lines[-1] += ','
                had_line = True
                lines.append("    test(and(")
            else:
                lines[-1] += ','

            if re == 2:
                if m:
                    lines.append("        in_list(field('{1}'), ',', '^{0}$', '{2}', '{3}')".\
                             format(tags, f, tval, fval))
                else:
                    lines.append("        contains(field('{1}'), '{0}', '{2}', '{3}')".\
                             format(tags, f, tval, fval))
            else:
                if m:
                    lines.append("        str_in_list(field('{1}'), ',', '{0}', '{2}', '{3}')".\
                             format(tags, f, tval, fval))
                else:
                    lines.append("        strcmp(field('{1}'), '{0}', '{3}', '{2}', '{3}')".\
                             format(tags, f, tval, fval))
            if a == 2:
                was_and = True
            else:
                was_and = False
                lines.append("    ), '{0}', '{1}')".format(c, nfc))

        res += '\n'.join(lines)
        res += ')\n'
        self.template = res
        res = ''
        for tb, cb, fb, nfcb, reb, ab, nb in zip(
                    self.tagboxes, self.colorboxes, self.colboxes,
                    self.nfcolorboxes, self.reboxes, self.andboxes, self.notboxes):
            t = unicode(tb.text()).strip()
            if t.endswith(','):
                t = t[:-1]
            c = unicode(cb.currentText()).strip()
            f = unicode(fb.currentText())
            nfc = unicode(nfcb.currentText()).strip()
            re = unicode(reb.checkState())
            a = unicode(ab.checkState())
            n = unicode(nb.checkState())
            if f and t and (a == '2' or c):
                res += '#' + t + ':|:' + c  + ':|:' + f + ':|:' + \
                            nfc + ':|:' + re + ':|:' + a + ':|:' + n + '\n'
        self.template += res
        return True

    def and_box_changed(self, state, line=None):
        if state == 2:
            self.colorboxes[line].setCurrentIndex(0)
            self.colorboxes[line].setEnabled(False)
            self.nfcolorboxes[line].setCurrentIndex(0)
            self.nfcolorboxes[line].setEnabled(False)
        else:
            self.colorboxes[line].setEnabled(True)
            self.nfcolorboxes[line].setEnabled(True)

    def accepted(self):
        if self.generate_program():
            self.accept()
        else:
            self.template = ''
