#!/usr/bin/env python
# License: GPLv3 Copyright: 2026, Kovid Goyal <kovid at kovidgoyal.net>

"""
Font data for camoufox, taken from the camoufox source repository at the tag
v156.0.1-beta.34. Refresh it from the files pythonlib/camoufox/essential-fonts.json and
pythonlib/camoufox/fonts.json at the tag of a newer camoufox release.
"""

# Fonts that must always be present in the generated font subset, because a
# real installation of the OS in question always has them
ESSENTIAL_FONTS: dict[str, tuple[str, ...]] = {
    'windows': (
        'Arial',
        'Arial Black',
        'Bahnschrift',
        'Calibri',
        'Calibri Light',
        'Cambria',
        'Cambria Math',
        'Candara',
        'Candara Light',
        'Comic Sans MS',
        'Consolas',
        'Constantia',
        'Corbel',
        'Corbel Light',
        'Courier',
        'Courier New',
        'Ebrima',
        'Franklin Gothic Medium',
        'Gabriola',
        'Gadugi',
        'Georgia',
        'Helvetica',
        'Impact',
        'Ink Free',
        'Javanese Text',
        'Leelawadee UI',
        'Leelawadee UI Semilight',
        'Lucida Console',
        'Lucida Sans Unicode',
        'MS Gothic',
        'MS PGothic',
        'MS Sans Serif',
        'MS Serif',
        'MS UI Gothic',
        'MV Boli',
        'Malgun Gothic',
        'Malgun Gothic Semilight',
        'Marlett',
        'Microsoft Himalaya',
        'Microsoft JhengHei',
        'Microsoft JhengHei Light',
        'Microsoft JhengHei UI',
        'Microsoft JhengHei UI Light',
        'Microsoft New Tai Lue',
        'Microsoft PhagsPa',
        'Microsoft Sans Serif',
        'Microsoft Tai Le',
        'Microsoft YaHei',
        'Microsoft YaHei Light',
        'Microsoft YaHei UI',
        'Microsoft YaHei UI Light',
        'Microsoft Yi Baiti',
        'MingLiU-ExtB',
        'MingLiU_HKSCS-ExtB',
        'MingLiU_MSCS-ExtB',
        'Mongolian Baiti',
        'Myanmar Text',
        'NSimSun',
        'Nirmala Text',
        'Nirmala Text Semilight',
        'Nirmala UI',
        'Nirmala UI Semilight',
        'PMingLiU-ExtB',
        'Palatino Linotype',
        'Roman',
        'Sans Serif Collection',
        'Segoe Fluent Icons',
        'Segoe MDL2 Assets',
        'Segoe Print',
        'Segoe Script',
        'Segoe UI',
        'Segoe UI Black',
        'Segoe UI Emoji',
        'Segoe UI Historic',
        'Segoe UI Light',
        'Segoe UI Semibold',
        'Segoe UI Semilight',
        'Segoe UI Symbol',
        'Segoe UI Variable',
        'Segoe UI Variable Display',
        'Segoe UI Variable Small',
        'Segoe UI Variable Text',
        'SimSun',
        'SimSun-ExtB',
        'Sitka Banner',
        'Sitka Display',
        'Sitka Heading',
        'Sitka Small',
        'Sitka Subheading',
        'Sitka Text',
        'Small Fonts',
        'Sylfaen',
        'Symbol',
        'Tahoma',
        'Times',
        'Times New Roman',
        'Trebuchet MS',
        'Twemoji Mozilla',
        'Verdana',
        'Webdings',
        'Wingdings',
        'Yu Gothic',
        'Yu Gothic Light',
        'Yu Gothic Medium',
        'Yu Gothic UI',
        'Yu Gothic UI Light',
        'Yu Gothic UI Semibold',
        'Yu Gothic UI Semilight',
        '宋体',
        '微軟正黑體',
        '微軟正黑體 Light',
        '微软雅黑',
        '微软雅黑 Light',
        '新宋体',
        '新細明體-ExtB',
        '游ゴシック',
        '游ゴシック Light',
        '游ゴシック Medium',
        '細明體-ExtB',
        '細明體_HKSCS-ExtB',
        '細明體_MSCS-ExtB',
        '맑은 고딕',
        '맑은 고딕 Semilight',
        'ＭＳ ゴシック',
        'ＭＳ Ｐゴシック',
    ),
    'macos': (
        'Academy Engraved LET',
        'Al Bayan',
        'Al Nile',
        'Al Tarikh',
        'American Typewriter',
        'American Typewriter Semibold',
        'Andale Mono',
        'Apple Braille',
        'Apple Chancery',
        'Apple Color Emoji',
        'Apple SD Gothic Neo',
        'Apple SD Gothic Neo ExtraBold',
        'Apple Symbols',
        'AppleGothic',
        'AppleMyungjo',
        'Arial',
        'Arial Black',
        'Arial Hebrew',
        'Arial Hebrew Scholar',
        'Arial Narrow',
        'Arial Rounded MT Bold',
        'Arial Unicode MS',
        'Athelas',
        'Avenir',
        'Avenir Black',
        'Avenir Black Oblique',
        'Avenir Book',
        'Avenir Heavy',
        'Avenir Light',
        'Avenir Medium',
        'Avenir Next',
        'Avenir Next Demi Bold',
        'Avenir Next Heavy',
        'Avenir Next Medium',
        'Avenir Next Ultra Light',
        'Ayuthaya',
        'Baghdad',
        'Bangla MN',
        'Bangla Sangam MN',
        'Baskerville',
        'Beirut',
        'Big Caslon',
        'Bodoni 72',
        'Bodoni 72 Oldstyle',
        'Bodoni 72 Smallcaps',
        'Bodoni Ornaments',
        'Bradley Hand',
        'Brush Script MT',
        'Chalkboard',
        'Chalkboard SE',
        'Chalkduster',
        'Charter',
        'Charter Black',
        'Cochin',
        'Comic Sans MS',
        'Copperplate',
        'Corsiva Hebrew',
        'Courier',
        'Courier New',
        'DIN Alternate',
        'DIN Condensed',
        'Damascus',
        'DecoType Naskh',
        'Devanagari MT',
        'Devanagari Sangam MN',
        'Didot',
        'Diwan Kufi',
        'Diwan Thuluth',
        'Euphemia UCAS',
        'Farah',
        'Farisi',
        'Futura',
        'Futura Bold',
        'GB18030 Bitmap',
        'Galvji',
        'Geeza Pro',
        'Geneva',
        'Georgia',
        'Gill Sans',
        'Grantha Sangam MN',
        'Gujarati MT',
        'Gujarati Sangam MN',
        'Gurmukhi MN',
        'Gurmukhi MT',
        'Gurmukhi Sangam MN',
        'Heiti SC',
        'Heiti TC',
        'Helvetica',
        'Helvetica Neue',
        'Hiragino Kaku Gothic Pro',
        'Hiragino Kaku Gothic Std',
        'Hiragino Kaku Gothic StdN',
        'Hiragino Maru Gothic Pro',
        'Hiragino Maru Gothic ProN',
        'Hiragino Maru Gothic ProN W4',
        'Hiragino Mincho Pro',
        'Hiragino Mincho ProN',
        'Hiragino Mincho ProN W3',
        'Hiragino Mincho ProN W6',
        'Hiragino Sans',
        'Hiragino Sans GB',
        'Hiragino Sans GB W3',
        'Hiragino Sans GB W6',
        'Hiragino Sans W0',
        'Hiragino Sans W1',
        'Hiragino Sans W2',
        'Hiragino Sans W3',
        'Hiragino Sans W4',
        'Hiragino Sans W5',
        'Hiragino Sans W6',
        'Hiragino Sans W7',
        'Hiragino Sans W8',
        'Hiragino Sans W9',
        'Hoefler Text',
        'Hoefler Text Ornaments',
        'ITF Devanagari',
        'ITF Devanagari Marathi',
        'Impact',
        'InaiMathi',
        'InaiMathi Bold',
        'Iowan Old Style',
        'Kailasa',
        'Kannada MN',
        'Kannada Sangam MN',
        'Khmer MN',
        'Khmer Sangam MN',
        'Kohinoor Bangla',
        'Kohinoor Devanagari',
        'Kohinoor Devanagari Medium',
        'Kohinoor Gujarati',
        'Kohinoor Telugu',
        'Kokonor',
        'Krungthep',
        'KufiStandardGK',
        'Lao MN',
        'Lao Sangam MN',
        'Lucida Grande',
        'Luminari',
        'Malayalam MN',
        'Malayalam Sangam MN',
        'Marker Felt',
        'Menlo',
        'Microsoft Sans Serif',
        'Mishafi',
        'Mishafi Gold',
        'Monaco',
        'Mshtakan',
        'MuktaMahee Bold',
        'MuktaMahee ExtraBold',
        'MuktaMahee ExtraLight',
        'MuktaMahee Light',
        'MuktaMahee Medium',
        'MuktaMahee Regular',
        'MuktaMahee SemiBold',
        'Muna',
        'Myanmar MN',
        'Myanmar Sangam MN',
        'Nadeem',
        'New Peninim MT',
        'Noteworthy',
        'Noto Nastaliq Urdu',
        'Noto Sans Adlam',
        'Noto Sans Armenian',
        'Noto Sans Armenian Blk',
        'Noto Sans Armenian ExtBd',
        'Noto Sans Armenian ExtLt',
        'Noto Sans Armenian Light',
        'Noto Sans Armenian Med',
        'Noto Sans Armenian SemBd',
        'Noto Sans Armenian Thin',
        'Noto Sans Avestan',
        'Noto Sans Bamum',
        'Noto Sans Bassa Vah',
        'Noto Sans Batak',
        'Noto Sans Bhaiksuki',
        'Noto Sans Buginese',
        'Noto Sans Buhid',
        'Noto Sans Canadian Aboriginal Regular',
        'Noto Sans Carian',
        'Noto Sans CaucAlban',
        'Noto Sans Chakma',
        'Noto Sans Cham',
        'Noto Sans Coptic',
        'Noto Sans Cuneiform',
        'Noto Sans Cypriot',
        'Noto Sans Duployan',
        'Noto Sans EgyptHiero',
        'Noto Sans Elbasan',
        'Noto Sans Glagolitic',
        'Noto Sans Gothic',
        'Noto Sans Gunjala Gondi',
        'Noto Sans HanifiRohg',
        'Noto Sans Hanunoo',
        'Noto Sans Hatran',
        'Noto Sans ImpAramaic',
        'Noto Sans InsPahlavi',
        'Noto Sans InsParthi',
        'Noto Sans Javanese',
        'Noto Sans Kaithi',
        'Noto Sans Kannada',
        'Noto Sans Kannada Black',
        'Noto Sans Kannada ExtraBold',
        'Noto Sans Kannada ExtraLight',
        'Noto Sans Kannada Light',
        'Noto Sans Kannada Medium',
        'Noto Sans Kannada SemiBold',
        'Noto Sans Kannada Thin',
        'Noto Sans Kayah Li',
        'Noto Sans Kharoshthi',
        'Noto Sans Khojki',
        'Noto Sans Khudawadi',
        'Noto Sans Lepcha',
        'Noto Sans Limbu',
        'Noto Sans Linear A',
        'Noto Sans Linear B',
        'Noto Sans Lisu',
        'Noto Sans Lycian',
        'Noto Sans Lydian',
        'Noto Sans Mahajani',
        'Noto Sans Mandaic',
        'Noto Sans Manichaean',
        'Noto Sans Marchen',
        'Noto Sans Masaram Gondi',
        'Noto Sans Mende Kikakui',
        'Noto Sans Meroitic',
        'Noto Sans Miao',
        'Noto Sans Modi',
        'Noto Sans Mongolian',
        'Noto Sans Mro',
        'Noto Sans Multani',
        'Noto Sans Myanmar',
        'Noto Sans Myanmar Blk',
        'Noto Sans Myanmar ExtBd',
        'Noto Sans Myanmar ExtLt',
        'Noto Sans Myanmar Light',
        'Noto Sans Myanmar Med',
        'Noto Sans Myanmar SemBd',
        'Noto Sans Myanmar Thin',
        'Noto Sans NKo',
        'Noto Sans Nabataean',
        'Noto Sans Newa',
        'Noto Sans Ol Chiki',
        'Noto Sans Old Italic',
        'Noto Sans Old Permic',
        'Noto Sans Old Turkic',
        'Noto Sans OldHung',
        'Noto Sans OldNorArab',
        'Noto Sans OldSouArab',
        'Noto Sans Oriya',
        'Noto Sans Osage',
        'Noto Sans Osmanya',
        'Noto Sans Pahawh Hmong',
        'Noto Sans Palmyrene',
        'Noto Sans PhagsPa',
        'Noto Sans Phoenician',
        'Noto Sans PsaPahlavi',
        'Noto Sans Rejang',
        'Noto Sans Samaritan',
        'Noto Sans Saurashtra',
        'Noto Sans Sharada',
        'Noto Sans Siddham',
        'Noto Sans SoraSomp',
        'Noto Sans Sundanese',
        'Noto Sans Syloti Nagri',
        'Noto Sans Syriac',
        'Noto Sans Tagalog',
        'Noto Sans Tagbanwa',
        'Noto Sans Tai Le',
        'Noto Sans Tai Tham',
        'Noto Sans Tai Viet',
        'Noto Sans Takri',
        'Noto Sans Thaana',
        'Noto Sans Tifinagh',
        'Noto Sans Tirhuta',
        'Noto Sans Ugaritic',
        'Noto Sans Vai',
        'Noto Sans Wancho',
        'Noto Sans Yi',
        'Noto Sans Zawgyi',
        'Noto Sans Zawgyi Blk',
        'Noto Sans Zawgyi ExtBd',
        'Noto Sans Zawgyi ExtLt',
        'Noto Sans Zawgyi Light',
        'Noto Sans Zawgyi Med',
        'Noto Sans Zawgyi SemBd',
        'Noto Sans Zawgyi Thin',
        'Noto Serif Ahom',
        'Noto Serif Balinese',
        'Noto Serif Hmong Nyiakeng',
        'Noto Serif Myanmar',
        'Noto Serif Myanmar Blk',
        'Noto Serif Myanmar ExtBd',
        'Noto Serif Myanmar ExtLt',
        'Noto Serif Myanmar Light',
        'Noto Serif Myanmar Med',
        'Noto Serif Myanmar SemBd',
        'Noto Serif Myanmar Thin',
        'Noto Serif Yezidi',
        'Optima',
        'Oriya MN',
        'Oriya Sangam MN',
        'PT Mono',
        'PT Sans',
        'PT Sans Caption',
        'PT Sans Narrow',
        'PT Serif',
        'PT Serif Caption',
        'Palatino',
        'Papyrus',
        'Party LET',
        'Phosphate',
        'PingFang HK',
        'PingFang SC',
        'PingFang TC',
        'Plantagenet Cherokee',
        'Raanana',
        'Rockwell',
        'STIX Two Math',
        'STIX Two Math Regular',
        'STIX Two Text',
        'STIX Two Text Regular',
        'STIXGeneral',
        'STIXIntegralsD',
        'STIXIntegralsSm',
        'STIXIntegralsUp',
        'STIXIntegralsUpD',
        'STIXIntegralsUpSm',
        'STIXNonUnicode',
        'STIXSizeFiveSym',
        'STIXSizeFourSym',
        'STIXSizeOneSym',
        'STIXSizeThreeSym',
        'STIXSizeTwoSym',
        'STIXVariants',
        'STSong',
        'Sana',
        'Sathu',
        'Savoye LET',
        'Shree Devanagari 714',
        'SignPainter-HouseScript',
        'Silom',
        'Sinhala MN',
        'Sinhala Sangam MN',
        'Skia',
        'Snell Roundhand',
        'Songti SC',
        'Songti TC',
        'Sukhumvit Set',
        'Superclarendon',
        'Symbol',
        'System Font',
        'Tahoma',
        'Tamil MN',
        'Tamil Sangam MN',
        'Telugu MN',
        'Telugu Sangam MN',
        'Thonburi',
        'Times',
        'Times New Roman',
        'Trattatello',
        'Trebuchet MS',
        'Verdana',
        'Waseem',
        'Webdings',
        'Wingdings',
        'Wingdings 2',
        'Wingdings 3',
        'Zapf Dingbats',
        'Zapfino',
    ),
    'linux': (
        'AR PL UKai CN',
        'AR PL UKai HK',
        'AR PL UKai TW',
        'AR PL UKai TW MBE',
        'AR PL UMing CN',
        'AR PL UMing HK',
        'AR PL UMing TW',
        'AR PL UMing TW MBE',
        'Arial',
        'Arial Narrow',
        'Avant Garde',
        'Bookman Old Style',
        'C059',
        'Calibri',
        'Cambria',
        'Century Schoolbook',
        'Courier',
        'Courier New',
        'D050000L',
        'DejaVu Sans',
        'DejaVu Sans Mono',
        'DejaVu Serif',
        'Droid Sans Fallback',
        'Helvetica',
        'Helvetica Narrow',
        'Liberation Mono',
        'Liberation Sans',
        'Liberation Sans Narrow',
        'Liberation Serif',
        'Nimbus Mono PS',
        'Nimbus Roman',
        'Nimbus Sans',
        'Nimbus Sans Narrow',
        'Noto Color Emoji',
        'Noto Kufi Arabic',
        'Noto Looped Lao',
        'Noto Looped Lao Bold',
        'Noto Looped Lao Regular',
        'Noto Looped Thai',
        'Noto Looped Thai Bold',
        'Noto Looped Thai Regular',
        'Noto Mono',
        'Noto Music',
        'Noto Naskh Arabic',
        'Noto Nastaliq Urdu',
        'Noto Rashi Hebrew',
        'Noto Sans',
        'Noto Sans Adlam',
        'Noto Sans Adlam Unjoined',
        'Noto Sans AnatoHiero',
        'Noto Sans Anatolian Hieroglyphs',
        'Noto Sans Arabic',
        'Noto Sans Armenian',
        'Noto Sans Avestan',
        'Noto Sans Balinese',
        'Noto Sans Bamum',
        'Noto Sans Bassa Vah',
        'Noto Sans Batak',
        'Noto Sans Bengali',
        'Noto Sans Bhaiksuki',
        'Noto Sans Brahmi',
        'Noto Sans Buginese',
        'Noto Sans Buhid',
        'Noto Sans CJK HK',
        'Noto Sans CJK JP',
        'Noto Sans CJK KR',
        'Noto Sans CJK SC',
        'Noto Sans CJK TC',
        'Noto Sans CanAborig',
        'Noto Sans Canadian Aboriginal',
        'Noto Sans Carian',
        'Noto Sans CaucAlban',
        'Noto Sans Caucasian Albanian',
        'Noto Sans Chakma',
        'Noto Sans Cham',
        'Noto Sans Cherokee',
        'Noto Sans Coptic',
        'Noto Sans Cuneiform',
        'Noto Sans Cypriot',
        'Noto Sans Deseret',
        'Noto Sans Devanagari',
        'Noto Sans Display',
        'Noto Sans Duployan',
        'Noto Sans EgyptHiero',
        'Noto Sans Egyptian Hieroglyphs',
        'Noto Sans Elbasan',
        'Noto Sans Elymaic',
        'Noto Sans Ethiopic',
        'Noto Sans Georgian',
        'Noto Sans Glagolitic',
        'Noto Sans Gothic',
        'Noto Sans Grantha',
        'Noto Sans Gujarati',
        'Noto Sans Gunjala Gondi',
        'Noto Sans Gurmukhi',
        'Noto Sans Hanifi Rohingya',
        'Noto Sans Hanunoo',
        'Noto Sans Hatran',
        'Noto Sans Hebrew',
        'Noto Sans ImpAramaic',
        'Noto Sans Imperial Aramaic',
        'Noto Sans Indic Siyaq Numbers',
        'Noto Sans InsPahlavi',
        'Noto Sans InsParthi',
        'Noto Sans Inscriptional Pahlavi',
        'Noto Sans Inscriptional Parthian',
        'Noto Sans Javanese',
        'Noto Sans Kaithi',
        'Noto Sans Kannada',
        'Noto Sans Kayah Li',
        'Noto Sans Kharoshthi',
        'Noto Sans Khmer',
        'Noto Sans Khojki',
        'Noto Sans Khudawadi',
        'Noto Sans Lao',
        'Noto Sans Lepcha',
        'Noto Sans Limbu',
        'Noto Sans Linear A',
        'Noto Sans Linear B',
        'Noto Sans Lisu',
        'Noto Sans Lycian',
        'Noto Sans Lydian',
        'Noto Sans Mahajani',
        'Noto Sans Malayalam',
        'Noto Sans Mandaic',
        'Noto Sans Manichaean',
        'Noto Sans Marchen',
        'Noto Sans Masaram Gondi',
        'Noto Sans Math',
        'Noto Sans Mayan Numerals',
        'Noto Sans Medefaidrin',
        'Noto Sans Meetei Mayek',
        'Noto Sans Mende Kikakui',
        'Noto Sans Meroitic',
        'Noto Sans Miao',
        'Noto Sans Modi',
        'Noto Sans Mongolian',
        'Noto Sans Mono',
        'Noto Sans Mono CJK HK',
        'Noto Sans Mono CJK JP',
        'Noto Sans Mono CJK KR',
        'Noto Sans Mono CJK SC',
        'Noto Sans Mono CJK TC',
        'Noto Sans Mro',
        'Noto Sans Multani',
        'Noto Sans Myanmar',
        'Noto Sans NKo',
        'Noto Sans Nabataean',
        'Noto Sans New Tai Lue',
        'Noto Sans Newa',
        'Noto Sans Nushu',
        'Noto Sans Ogham',
        'Noto Sans Ol Chiki',
        'Noto Sans Old Hungarian',
        'Noto Sans Old Italic',
        'Noto Sans Old North Arabian',
        'Noto Sans Old Permic',
        'Noto Sans Old Persian',
        'Noto Sans Old Sogdian',
        'Noto Sans Old South Arabian',
        'Noto Sans Old Turkic',
        'Noto Sans OldHung',
        'Noto Sans OldNorArab',
        'Noto Sans OldSouArab',
        'Noto Sans Oriya',
        'Noto Sans Osage',
        'Noto Sans Osmanya',
        'Noto Sans Pahawh Hmong',
        'Noto Sans Palmyrene',
        'Noto Sans Pau Cin Hau',
        'Noto Sans PhagsPa',
        'Noto Sans Phoenician',
        'Noto Sans PsaPahlavi',
        'Noto Sans Psalter Pahlavi',
        'Noto Sans Rejang',
        'Noto Sans Runic',
        'Noto Sans Samaritan',
        'Noto Sans Saurashtra',
        'Noto Sans Sharada',
        'Noto Sans Shavian',
        'Noto Sans Siddham',
        'Noto Sans SignWrit',
        'Noto Sans SignWriting',
        'Noto Sans Sinhala',
        'Noto Sans Sogdian',
        'Noto Sans Sora Sompeng',
        'Noto Sans Soyombo',
        'Noto Sans Sundanese',
        'Noto Sans Syloti Nagri',
        'Noto Sans Symbols',
        'Noto Sans Symbols2',
        'Noto Sans Syriac',
        'Noto Sans Tagalog',
        'Noto Sans Tagbanwa',
        'Noto Sans Tai Le',
        'Noto Sans Tai Tham',
        'Noto Sans Tai Viet',
        'Noto Sans Takri',
        'Noto Sans Tamil',
        'Noto Sans Tamil Supplement',
        'Noto Sans Telugu',
        'Noto Sans Thaana',
        'Noto Sans Thai',
        'Noto Sans Tifinagh',
        'Noto Sans Tifinagh APT',
        'Noto Sans Tifinagh Adrar',
        'Noto Sans Tifinagh Agraw Imazighen',
        'Noto Sans Tifinagh Ahaggar',
        'Noto Sans Tifinagh Air',
        'Noto Sans Tifinagh Azawagh',
        'Noto Sans Tifinagh Ghat',
        'Noto Sans Tifinagh Hawad',
        'Noto Sans Tifinagh Rhissa Ixa',
        'Noto Sans Tifinagh SIL',
        'Noto Sans Tifinagh Tawellemmet',
        'Noto Sans Tirhuta',
        'Noto Sans Ugaritic',
        'Noto Sans Vai',
        'Noto Sans Wancho',
        'Noto Sans Warang Citi',
        'Noto Sans Yi',
        'Noto Sans Zanabazar',
        'Noto Sans Zanabazar Square',
        'Noto Serif',
        'Noto Serif Ahom',
        'Noto Serif Armenian',
        'Noto Serif Balinese',
        'Noto Serif Bengali',
        'Noto Serif CJK HK',
        'Noto Serif CJK JP',
        'Noto Serif CJK KR',
        'Noto Serif CJK SC',
        'Noto Serif CJK TC',
        'Noto Serif Devanagari',
        'Noto Serif Display',
        'Noto Serif Dogra',
        'Noto Serif Ethiopic',
        'Noto Serif Georgian',
        'Noto Serif Grantha',
        'Noto Serif Gujarati',
        'Noto Serif Gurmukhi',
        'Noto Serif Hebrew',
        'Noto Serif Hmong Nyiakeng',
        'Noto Serif Kannada',
        'Noto Serif Khmer',
        'Noto Serif Khojki',
        'Noto Serif Lao',
        'Noto Serif Malayalam',
        'Noto Serif Myanmar',
        'Noto Serif Sinhala',
        'Noto Serif Tamil',
        'Noto Serif Tamil Slanted',
        'Noto Serif Tangut',
        'Noto Serif Telugu',
        'Noto Serif Thai',
        'Noto Serif Tibetan',
        'Noto Serif Yezidi',
        'Noto Traditional Nushu',
        'OpenSymbol',
        'P052',
        'Palatino',
        'Palatino Linotype',
        'Standard Symbols PS',
        'Symbol',
        'Times',
        'Times New Roman',
        'URW Bookman',
        'URW Gothic',
        'Ubuntu',
        'Ubuntu Mono',
        'Ubuntu Sans',
        'Ubuntu Sans Mono',
        'Z003',
        'Zapf Chancery',
    ),
}

# The fonts a real installation of the OS in question can report, used for
# newer camoufox bundles if the list for the installed camoufox version cannot
# be downloaded, see camoufox_font_lists()
FALLBACK_REPORTABLE_FONTS: dict[str, tuple[str, ...]] = {
    'windows': (
        'Agency FB',
        'Alef',
        'Algerian',
        'Amiri',
        'Amiri Quran',
        'Anonymous Pro',
        'Arial',
        'Arial Black',
        'Arial Nova',
        'Bahnschrift',
        'Barlow',
        'Baskerville Old Face',
        'Bauhaus 93',
        'Bebas Neue',
        'Bell MT',
        'Berlin Sans FB',
        'Berlin Sans FB Demi',
        'Bernard MT Condensed',
        'Blackadder ITC',
        'Bodoni MT',
        'Bodoni MT Black',
        'Bodoni MT Condensed',
        'Bodoni MT Poster Compressed',
        'Book Antiqua',
        'Bookman Old Style',
        'Bookshelf Symbol 7',
        'Bradley Hand ITC',
        'Britannic Bold',
        'Broadway',
        'Brush Script MT',
        'Cabin',
        'Caladea',
        'Calibri',
        'Calibri Light',
        'Californian FB',
        'Calisto MT',
        'Cambria',
        'Cambria Math',
        'Candara',
        'Candara Light',
        'Carlito',
        'Cascadia Code',
        'Cascadia Mono',
        'Castellar',
        'Centaur',
        'Century',
        'Century Gothic',
        'Century Schoolbook',
        'Chiller',
        'Colonna MT',
        'Comic Sans MS',
        'Consolas',
        'Constantia',
        'Cooper Black',
        'Copperplate Gothic Bold',
        'Copperplate Gothic Light',
        'Corbel',
        'Corbel Light',
        'Courier',
        'Courier New',
        'Curlz MT',
        'DM Sans',
        'David Libre',
        'DejaVu Math TeX Gyre',
        'DejaVu Sans',
        'DejaVu Sans Condensed',
        'DejaVu Sans Light',
        'DejaVu Sans Mono',
        'DejaVu Serif',
        'DejaVu Serif Condensed',
        'Dubai',
        'Ebrima',
        'Edwardian Script ITC',
        'Elephant',
        'Engravers MT',
        'Eras Bold ITC',
        'Eras Demi ITC',
        'Eras Light ITC',
        'Eras Medium ITC',
        'Felix Titling',
        'Fira Code',
        'Fira Mono',
        'Fira Sans',
        'Footlight MT Light',
        'Forte',
        'Franklin Gothic Book',
        'Franklin Gothic Demi',
        'Franklin Gothic Demi Cond',
        'Franklin Gothic Heavy',
        'Franklin Gothic Medium',
        'Freestyle Script',
        'French Script MT',
        'Gabriola',
        'Gadugi',
        'Garamond',
        'Gentium Basic',
        'Gentium Book Basic',
        'Georgia',
        'Georgia Pro',
        'Gigi',
        'Gill Sans MT',
        'Gill Sans MT Condensed',
        'Gill Sans MT Ext Condensed Bold',
        'Gill Sans Nova',
        'Gill Sans Ultra Bold',
        'Gill Sans Ultra Bold Condensed',
        'Gloucester MT Extra Condensed',
        'Goudy Old Style',
        'Goudy Stout',
        'Hack',
        'Haettenschweiler',
        'Harlow Solid Italic',
        'Harrington',
        'Heebo',
        'Helvetica',
        'High Tower Text',
        'HoloLens MDL2 Assets',
        'IBM Plex Mono',
        'Impact',
        'Imprint MT Shadow',
        'Inconsolata',
        'Informal Roman',
        'Ink Free',
        'Inter',
        'Iosevka',
        'Javanese Text',
        'JetBrains Mono',
        'Jokerman',
        'Josefin Sans',
        'Juice ITC',
        'Karla',
        'Kristen ITC',
        'Kunstler Script',
        'Lato',
        'Leelawadee UI',
        'Leelawadee UI Semilight',
        'Liberation Mono',
        'Liberation Sans',
        'Liberation Sans Narrow',
        'Liberation Serif',
        'Lucida Bright',
        'Lucida Calligraphy',
        'Lucida Console',
        'Lucida Fax',
        'Lucida Handwriting',
        'Lucida Sans Typewriter',
        'Lucida Sans Unicode',
        'MS Gothic',
        'MS Outlook',
        'MS PGothic',
        'MS Reference Sans Serif',
        'MS Reference Specialty',
        'MS Sans Serif',
        'MS Serif',
        'MS UI Gothic',
        'MT Extra',
        'MV Boli',
        'Magneto',
        'Maiandra GD',
        'Malgun Gothic',
        'Malgun Gothic Semilight',
        'Manrope',
        'Marlett',
        'Matura MT Script Capitals',
        'Merriweather',
        'Meslo LG L',
        'Meslo LG M',
        'Meslo LG S',
        'Microsoft Himalaya',
        'Microsoft JhengHei',
        'Microsoft JhengHei Light',
        'Microsoft JhengHei UI',
        'Microsoft JhengHei UI Light',
        'Microsoft New Tai Lue',
        'Microsoft PhagsPa',
        'Microsoft Sans Serif',
        'Microsoft Tai Le',
        'Microsoft YaHei',
        'Microsoft YaHei Light',
        'Microsoft YaHei UI',
        'Microsoft YaHei UI Light',
        'Microsoft Yi Baiti',
        'MingLiU-ExtB',
        'MingLiU_HKSCS-ExtB',
        'MingLiU_MSCS-ExtB',
        'Mistral',
        'Modern No. 20',
        'Mongolian Baiti',
        'Monotype Corsiva',
        'Montserrat',
        'Mukta',
        'Myanmar Text',
        'NSimSun',
        'Neue Haas Grotesk Text Pro',
        'Niagara Engraved',
        'Niagara Solid',
        'Nirmala Text',
        'Nirmala Text Semilight',
        'Nirmala UI',
        'Nirmala UI Semilight',
        'Noto Kufi Arabic',
        'Noto Mono',
        'Noto Naskh Arabic',
        'Noto Sans',
        'Noto Sans Arabic',
        'Noto Sans Armenian',
        'Noto Sans Georgian',
        'Noto Sans Hebrew',
        'Noto Sans Lao',
        'Noto Sans Lisu',
        'Noto Serif',
        'Noto Serif Armenian',
        'Noto Serif Georgian',
        'Noto Serif Hebrew',
        'Noto Serif Lao',
        'Nunito',
        'Nunito Sans',
        'OCR A Extended',
        'Old English Text MT',
        'Onyx',
        'Open Sans',
        'OpenSymbol',
        'Oswald',
        'Overpass Mono',
        'PMingLiU-ExtB',
        'PT Mono',
        'PT Sans',
        'PT Serif',
        'Palace Script MT',
        'Palatino Linotype',
        'Papyrus',
        'Parchment',
        'Perpetua',
        'Perpetua Titling MT',
        'Playbill',
        'Playfair Display',
        'Poor Richard',
        'Poppins',
        'Pristina',
        'Quicksand',
        'Rage Italic',
        'Raleway',
        'Ravie',
        'Reem Kufi',
        'Roboto',
        'Roboto Condensed',
        'Roboto Mono',
        'Roboto Slab',
        'Rockwell',
        'Rockwell Condensed',
        'Rockwell Extra Bold',
        'Rockwell Nova',
        'Roman',
        'Rubik',
        'Sans Serif Collection',
        'Scheherazade',
        'Script MT Bold',
        'Segoe Fluent Icons',
        'Segoe MDL2 Assets',
        'Segoe Print',
        'Segoe Script',
        'Segoe UI',
        'Segoe UI Black',
        'Segoe UI Emoji',
        'Segoe UI Historic',
        'Segoe UI Light',
        'Segoe UI Semibold',
        'Segoe UI Semilight',
        'Segoe UI Symbol',
        'Segoe UI Variable',
        'Segoe UI Variable Display',
        'Segoe UI Variable Small',
        'Segoe UI Variable Text',
        'Showcard Gothic',
        'SimSun',
        'SimSun-ExtB',
        'Sitka Banner',
        'Sitka Display',
        'Sitka Heading',
        'Sitka Small',
        'Sitka Subheading',
        'Sitka Text',
        'Small Fonts',
        'Snap ITC',
        'Source Code Pro',
        'Source Sans 3',
        'Source Serif 4',
        'Space Mono',
        'Stencil',
        'Sylfaen',
        'Symbol',
        'Tahoma',
        'Tempus Sans ITC',
        'Times',
        'Times New Roman',
        'Titillium Web',
        'Trebuchet MS',
        'Tw Cen MT',
        'Tw Cen MT Condensed',
        'Tw Cen MT Condensed Extra Bold',
        'Twemoji Mozilla',
        'Verdana',
        'Verdana Pro',
        'Victor Mono',
        'Viner Hand ITC',
        'Vivaldi',
        'Vladimir Script',
        'Webdings',
        'Wide Latin',
        'Wingdings',
        'Work Sans',
        'Yu Gothic',
        'Yu Gothic Light',
        'Yu Gothic Medium',
        'Yu Gothic UI',
        'Yu Gothic UI Light',
        'Yu Gothic UI Semibold',
        'Yu Gothic UI Semilight',
        '宋体',
        '微軟正黑體',
        '微軟正黑體 Light',
        '微软雅黑',
        '微软雅黑 Light',
        '新宋体',
        '新細明體-ExtB',
        '游ゴシック',
        '游ゴシック Light',
        '游ゴシック Medium',
        '細明體-ExtB',
        '細明體_HKSCS-ExtB',
        '細明體_MSCS-ExtB',
        '맑은 고딕',
        '맑은 고딕 Semilight',
        'ＭＳ ゴシック',
        'ＭＳ Ｐゴシック',
    ),
    'macos': (
        'Academy Engraved LET',
        'Al Bayan',
        'Al Nile',
        'Al Tarikh',
        'American Typewriter',
        'American Typewriter Semibold',
        'Andale Mono',
        'Anonymous Pro',
        'Apple Braille',
        'Apple Chancery',
        'Apple Color Emoji',
        'Apple SD Gothic Neo',
        'Apple SD Gothic Neo ExtraBold',
        'Apple SD 산돌고딕 Neo',
        'Apple Symbols',
        'AppleGothic',
        'AppleMyungjo',
        'Arial',
        'Arial Black',
        'Arial Hebrew',
        'Arial Hebrew Scholar',
        'Arial Narrow',
        'Arial Rounded MT Bold',
        'Arial Unicode MS',
        'Athelas',
        'Avenir',
        'Avenir Black',
        'Avenir Black Oblique',
        'Avenir Book',
        'Avenir Heavy',
        'Avenir Light',
        'Avenir Medium',
        'Avenir Next',
        'Avenir Next Condensed',
        'Avenir Next Condensed Demi Bold',
        'Avenir Next Condensed Heavy',
        'Avenir Next Condensed Medium',
        'Avenir Next Condensed Ultra Light',
        'Avenir Next Demi Bold',
        'Avenir Next Heavy',
        'Avenir Next Medium',
        'Avenir Next Ultra Light',
        'Ayuthaya',
        'Baghdad',
        'Bangla MN',
        'Bangla Sangam MN',
        'Barlow',
        'Baskerville',
        'Bebas Neue',
        'Beirut',
        'Big Caslon',
        'Bodoni 72',
        'Bodoni 72 Oldstyle',
        'Bodoni 72 Smallcaps',
        'Bodoni Ornaments',
        'Bradley Hand',
        'Brush Script MT',
        'Cabin',
        'Chalkboard',
        'Chalkboard SE',
        'Chalkduster',
        'Charter',
        'Charter Black',
        'Cochin',
        'Comic Sans MS',
        'Copperplate',
        'Corsiva Hebrew',
        'Courier',
        'Courier New',
        'Czcionka systemowa',
        'DIN Alternate',
        'DIN Condensed',
        'DM Sans',
        'Damascus',
        'DecoType Naskh',
        'Devanagari MT',
        'Devanagari Sangam MN',
        'Didot',
        'Diwan Kufi',
        'Diwan Thuluth',
        'Euphemia UCAS',
        'Farah',
        'Farisi',
        'Fira Code',
        'Fira Mono',
        'Fira Sans',
        'Font Sistem',
        'Font de sistem',
        'Font di sistema',
        'Font sustava',
        'Fonte do Sistema',
        'Futura',
        'Futura Bold',
        'GB18030 Bitmap',
        'Galvji',
        'Geeza Pro',
        'Geneva',
        'Georgia',
        'Gill Sans',
        'Grantha Sangam MN',
        'Gujarati MT',
        'Gujarati Sangam MN',
        'Gurmukhi MN',
        'Gurmukhi MT',
        'Gurmukhi Sangam MN',
        'Hack',
        'Heebo',
        'Heiti SC',
        'Heiti TC',
        'Heiti-간체',
        'Heiti-번체',
        'Helvetica',
        'Helvetica Neue',
        'Herculanum',
        'Hiragino Kaku Gothic Pro',
        'Hiragino Kaku Gothic Pro W3',
        'Hiragino Kaku Gothic Pro W6',
        'Hiragino Kaku Gothic ProN',
        'Hiragino Kaku Gothic ProN W3',
        'Hiragino Kaku Gothic ProN W6',
        'Hiragino Kaku Gothic Std',
        'Hiragino Kaku Gothic Std W8',
        'Hiragino Kaku Gothic StdN',
        'Hiragino Kaku Gothic StdN W8',
        'Hiragino Maru Gothic Pro',
        'Hiragino Maru Gothic Pro W4',
        'Hiragino Maru Gothic ProN',
        'Hiragino Maru Gothic ProN W4',
        'Hiragino Mincho Pro',
        'Hiragino Mincho Pro W3',
        'Hiragino Mincho Pro W6',
        'Hiragino Mincho ProN',
        'Hiragino Mincho ProN W3',
        'Hiragino Mincho ProN W6',
        'Hiragino Sans',
        'Hiragino Sans GB',
        'Hiragino Sans GB W3',
        'Hiragino Sans GB W6',
        'Hiragino Sans W0',
        'Hiragino Sans W1',
        'Hiragino Sans W2',
        'Hiragino Sans W3',
        'Hiragino Sans W4',
        'Hiragino Sans W5',
        'Hiragino Sans W6',
        'Hiragino Sans W7',
        'Hiragino Sans W8',
        'Hiragino Sans W9',
        'Hoefler Text',
        'Hoefler Text Ornaments',
        'IBM Plex Mono',
        'ITF Devanagari',
        'ITF Devanagari Marathi',
        'Impact',
        'InaiMathi',
        'InaiMathi Bold',
        'Inconsolata',
        'Inter',
        'Iosevka',
        'Iowan Old Style',
        'Iowan Old Style Black',
        'JetBrains Mono',
        'Josefin Sans',
        'Järjestelmäfontti',
        'Kailasa',
        'Kannada MN',
        'Kannada Sangam MN',
        'Karla',
        'Kefa',
        'Khmer MN',
        'Khmer Sangam MN',
        'Kohinoor Bangla',
        'Kohinoor Devanagari',
        'Kohinoor Devanagari Medium',
        'Kohinoor Gujarati',
        'Kohinoor Telugu',
        'Kokonor',
        'Krungthep',
        'KufiStandardGK',
        'Lao MN',
        'Lao Sangam MN',
        'Lato',
        'Lucida Grande',
        'Luminari',
        'Malayalam MN',
        'Malayalam Sangam MN',
        'Manrope',
        'Marion',
        'Marker Felt',
        'Menlo',
        'Merriweather',
        'Meslo LG L',
        'Meslo LG M',
        'Meslo LG S',
        'Microsoft Sans Serif',
        'Mishafi',
        'Mishafi Gold',
        'Monaco',
        'Montserrat',
        'Mshtakan',
        'Mukta',
        'Mukta Mahee',
        'MuktaMahee Bold',
        'MuktaMahee ExtraBold',
        'MuktaMahee ExtraLight',
        'MuktaMahee Light',
        'MuktaMahee Medium',
        'MuktaMahee Regular',
        'MuktaMahee SemiBold',
        'Muna',
        'Myanmar MN',
        'Myanmar Sangam MN',
        'Nadeem',
        'New Peninim MT',
        'Noteworthy',
        'Noto Nastaliq Urdu',
        'Noto Sans Adlam',
        'Noto Sans Armenian',
        'Noto Sans Armenian Blk',
        'Noto Sans Armenian ExtBd',
        'Noto Sans Armenian ExtLt',
        'Noto Sans Armenian Light',
        'Noto Sans Armenian Med',
        'Noto Sans Armenian SemBd',
        'Noto Sans Armenian Thin',
        'Noto Sans Avestan',
        'Noto Sans Bamum',
        'Noto Sans Bassa Vah',
        'Noto Sans Batak',
        'Noto Sans Bhaiksuki',
        'Noto Sans Brahmi',
        'Noto Sans Buginese',
        'Noto Sans Buhid',
        'Noto Sans CanAborig',
        'Noto Sans Canadian Aboriginal',
        'Noto Sans Canadian Aboriginal Regular',
        'Noto Sans Carian',
        'Noto Sans CaucAlban',
        'Noto Sans Caucasian Albanian',
        'Noto Sans Chakma',
        'Noto Sans Cham',
        'Noto Sans Coptic',
        'Noto Sans Cuneiform',
        'Noto Sans Cypriot',
        'Noto Sans Duployan',
        'Noto Sans EgyptHiero',
        'Noto Sans Egyptian Hieroglyphs',
        'Noto Sans Elbasan',
        'Noto Sans Glagolitic',
        'Noto Sans Gothic',
        'Noto Sans Gunjala Gondi',
        'Noto Sans Hanifi Rohingya',
        'Noto Sans HanifiRohg',
        'Noto Sans Hanunoo',
        'Noto Sans Hatran',
        'Noto Sans ImpAramaic',
        'Noto Sans Imperial Aramaic',
        'Noto Sans InsPahlavi',
        'Noto Sans InsParthi',
        'Noto Sans Inscriptional Pahlavi',
        'Noto Sans Inscriptional Parthian',
        'Noto Sans Javanese',
        'Noto Sans Kaithi',
        'Noto Sans Kannada',
        'Noto Sans Kannada Black',
        'Noto Sans Kannada ExtraBold',
        'Noto Sans Kannada ExtraLight',
        'Noto Sans Kannada Light',
        'Noto Sans Kannada Medium',
        'Noto Sans Kannada SemiBold',
        'Noto Sans Kannada Thin',
        'Noto Sans Kayah Li',
        'Noto Sans Kharoshthi',
        'Noto Sans Khojki',
        'Noto Sans Khudawadi',
        'Noto Sans Lepcha',
        'Noto Sans Limbu',
        'Noto Sans Linear A',
        'Noto Sans Linear B',
        'Noto Sans Lisu',
        'Noto Sans Lycian',
        'Noto Sans Lydian',
        'Noto Sans Mahajani',
        'Noto Sans Mandaic',
        'Noto Sans Manichaean',
        'Noto Sans Marchen',
        'Noto Sans Masaram Gondi',
        'Noto Sans Meetei Mayek',
        'Noto Sans Mende Kikakui',
        'Noto Sans Meroitic',
        'Noto Sans Miao',
        'Noto Sans Modi',
        'Noto Sans Mongolian',
        'Noto Sans Mro',
        'Noto Sans Multani',
        'Noto Sans Myanmar',
        'Noto Sans Myanmar Blk',
        'Noto Sans Myanmar ExtBd',
        'Noto Sans Myanmar ExtLt',
        'Noto Sans Myanmar Light',
        'Noto Sans Myanmar Med',
        'Noto Sans Myanmar SemBd',
        'Noto Sans Myanmar Thin',
        'Noto Sans NKo',
        'Noto Sans Nabataean',
        'Noto Sans New Tai Lue',
        'Noto Sans Newa',
        'Noto Sans Ol Chiki',
        'Noto Sans Old Hungarian',
        'Noto Sans Old Italic',
        'Noto Sans Old North Arabian',
        'Noto Sans Old Permic',
        'Noto Sans Old Persian',
        'Noto Sans Old South Arabian',
        'Noto Sans Old Turkic',
        'Noto Sans OldHung',
        'Noto Sans OldNorArab',
        'Noto Sans OldSouArab',
        'Noto Sans Oriya',
        'Noto Sans Osage',
        'Noto Sans Osmanya',
        'Noto Sans Pahawh Hmong',
        'Noto Sans Palmyrene',
        'Noto Sans Pau Cin Hau',
        'Noto Sans PhagsPa',
        'Noto Sans Phoenician',
        'Noto Sans PsaPahlavi',
        'Noto Sans Psalter Pahlavi',
        'Noto Sans Rejang',
        'Noto Sans Samaritan',
        'Noto Sans Saurashtra',
        'Noto Sans Sharada',
        'Noto Sans Siddham',
        'Noto Sans Sora Sompeng',
        'Noto Sans SoraSomp',
        'Noto Sans Sundanese',
        'Noto Sans Syloti Nagri',
        'Noto Sans Syriac',
        'Noto Sans Tagalog',
        'Noto Sans Tagbanwa',
        'Noto Sans Tai Le',
        'Noto Sans Tai Tham',
        'Noto Sans Tai Viet',
        'Noto Sans Takri',
        'Noto Sans Thaana',
        'Noto Sans Tifinagh',
        'Noto Sans Tirhuta',
        'Noto Sans Ugaritic',
        'Noto Sans Vai',
        'Noto Sans Wancho',
        'Noto Sans Warang Citi',
        'Noto Sans Yi',
        'Noto Sans Zawgyi',
        'Noto Sans Zawgyi Blk',
        'Noto Sans Zawgyi ExtBd',
        'Noto Sans Zawgyi ExtLt',
        'Noto Sans Zawgyi Light',
        'Noto Sans Zawgyi Med',
        'Noto Sans Zawgyi SemBd',
        'Noto Sans Zawgyi Thin',
        'Noto Serif Ahom',
        'Noto Serif Balinese',
        'Noto Serif Hmong Nyiakeng',
        'Noto Serif Myanmar',
        'Noto Serif Myanmar Blk',
        'Noto Serif Myanmar ExtBd',
        'Noto Serif Myanmar ExtLt',
        'Noto Serif Myanmar Light',
        'Noto Serif Myanmar Med',
        'Noto Serif Myanmar SemBd',
        'Noto Serif Myanmar Thin',
        'Noto Serif Yezidi',
        'Nunito',
        'Nunito Sans',
        'Open Sans',
        'Optima',
        'Oriya MN',
        'Oriya Sangam MN',
        'Oswald',
        'Overpass Mono',
        'PT Mono',
        'PT Sans',
        'PT Sans Caption',
        'PT Sans Narrow',
        'PT Serif',
        'PT Serif Caption',
        'Palatino',
        'Papyrus',
        'Party LET',
        'Phosphate',
        'Phông chữ Hệ thống',
        'PingFang HK',
        'PingFang SC',
        'PingFang TC',
        'Plantagenet Cherokee',
        'Playfair Display',
        'Police système',
        'Poppins',
        'Quicksand',
        'Raanana',
        'Raleway',
        'Rendszerbetűtípus',
        'Roboto',
        'Roboto Condensed',
        'Roboto Mono',
        'Roboto Slab',
        'Rockwell',
        'Rubik',
        'STIX Two Math',
        'STIX Two Math Regular',
        'STIX Two Text',
        'STIX Two Text Regular',
        'STIXGeneral',
        'STIXIntegralsD',
        'STIXIntegralsSm',
        'STIXIntegralsUp',
        'STIXIntegralsUpD',
        'STIXIntegralsUpSm',
        'STIXNonUnicode',
        'STIXSizeFiveSym',
        'STIXSizeFourSym',
        'STIXSizeOneSym',
        'STIXSizeThreeSym',
        'STIXSizeTwoSym',
        'STIXVariants',
        'STSong',
        'Sana',
        'Sathu',
        'Savoye LET',
        'Seravek',
        'Seravek ExtraLight',
        'Seravek Light',
        'Seravek Medium',
        'Shree Devanagari 714',
        'SignPainter',
        'SignPainter-HouseScript',
        'Silom',
        'Sinhala MN',
        'Sinhala Sangam MN',
        'Sistem Fontu',
        'Skia',
        'Snell Roundhand',
        'Songti SC',
        'Songti TC',
        'Source Code Pro',
        'Source Sans 3',
        'Source Serif 4',
        'Space Mono',
        'Sukhumvit Set',
        'Superclarendon',
        'Symbol',
        'Systeemlettertype',
        'System Font',
        'Systemschrift',
        'Systemskrift',
        'Systemtypsnitt',
        'Systémové písmo',
        'Tahoma',
        'Tamil MN',
        'Tamil Sangam MN',
        'Telugu MN',
        'Telugu Sangam MN',
        'Thonburi',
        'Times',
        'Times New Roman',
        'Tipo de letra del sistema',
        'Tipo de letra do sistema',
        'Tipus de lletra del sistema',
        'Titillium Web',
        'Trattatello',
        'Trebuchet MS',
        'Verdana',
        'Victor Mono',
        'Waseem',
        'Webdings',
        'Wingdings',
        'Wingdings 2',
        'Wingdings 3',
        'Work Sans',
        'Zapf Dingbats',
        'Zapfino',
        'Γραμματοσειρά συστήματος',
        'Системний шрифт',
        'Системный шрифт',
        'גופן מערכת',
        'البيان',
        'التاريخ',
        'النيل',
        'بغداد',
        'بيروت',
        'جيزة',
        'خط النظام',
        'دمشق',
        'ديوان ثلث',
        'ديوان كوفي',
        'صنعاء',
        'فارسي',
        'فرح',
        'كوفي',
        'منى',
        'مِصحفي',
        'مِصحفي ذهبي',
        'نديم',
        'نسخ',
        'وسيم',
        'कोहिनूर देवनागरी',
        'แบบอักษรระบบ',
        'システムフォント',
        'ヒラギノ丸ゴ Pro',
        'ヒラギノ丸ゴ Pro W4',
        'ヒラギノ丸ゴ ProN',
        'ヒラギノ丸ゴ ProN W4',
        'ヒラギノ明朝 Pro',
        'ヒラギノ明朝 Pro W3',
        'ヒラギノ明朝 Pro W6',
        'ヒラギノ明朝 ProN',
        'ヒラギノ明朝 ProN W3',
        'ヒラギノ明朝 ProN W6',
        'ヒラギノ角ゴ Pro',
        'ヒラギノ角ゴ Pro W3',
        'ヒラギノ角ゴ Pro W6',
        'ヒラギノ角ゴ ProN',
        'ヒラギノ角ゴ ProN W3',
        'ヒラギノ角ゴ ProN W6',
        'ヒラギノ角ゴ Std',
        'ヒラギノ角ゴ Std W8',
        'ヒラギノ角ゴ StdN',
        'ヒラギノ角ゴ StdN W8',
        'ヒラギノ角ゴ 簡体中文',
        'ヒラギノ角ゴ 簡体中文 W3',
        'ヒラギノ角ゴ 簡体中文 W6',
        'ヒラギノ角ゴシック',
        'ヒラギノ角ゴシック W0',
        'ヒラギノ角ゴシック W1',
        'ヒラギノ角ゴシック W2',
        'ヒラギノ角ゴシック W3',
        'ヒラギノ角ゴシック W4',
        'ヒラギノ角ゴシック W5',
        'ヒラギノ角ゴシック W6',
        'ヒラギノ角ゴシック W7',
        'ヒラギノ角ゴシック W8',
        'ヒラギノ角ゴシック W9',
        '冬青黑体简体中文',
        '冬青黑体简体中文 W3',
        '冬青黑体简体中文 W6',
        '冬青黑體簡體中文',
        '冬青黑體簡體中文 W3',
        '冬青黑體簡體中文 W6',
        '宋体-简',
        '宋体-繁',
        '宋體-簡',
        '宋體-繁',
        '系統字體',
        '系统字体',
        '苹方-港',
        '苹方-简',
        '苹方-繁',
        '蘋方-港',
        '蘋方-簡',
        '蘋方-繁',
        '黑体-简',
        '黑体-繁',
        '黑體-簡',
        '黑體-繁',
        '黒体-簡',
        '黒体-繁',
        '시스템 서체',
    ),
    'linux': (
        'AR PL UKai CN',
        'AR PL UKai HK',
        'AR PL UKai TW',
        'AR PL UKai TW MBE',
        'AR PL UMing CN',
        'AR PL UMing HK',
        'AR PL UMing TW',
        'AR PL UMing TW MBE',
        'Alef',
        'Amiri',
        'Amiri Quran',
        'Anonymous Pro',
        'Arial',
        'Arial Narrow',
        'Arimo',
        'Avant Garde',
        'Barlow',
        'Bebas Neue',
        'Bookman Old Style',
        'C059',
        'Cabin',
        'Caladea',
        'Calibri',
        'Cambria',
        'Carlito',
        'Century Schoolbook',
        'Courier',
        'Courier New',
        'Cousine',
        'D050000L',
        'DM Sans',
        'David CLM',
        'David Libre',
        'DejaVu Math TeX Gyre',
        'DejaVu Sans',
        'DejaVu Sans Condensed',
        'DejaVu Sans Light',
        'DejaVu Sans Mono',
        'DejaVu Serif',
        'DejaVu Serif Condensed',
        'Droid Sans Fallback',
        'Fira Code',
        'Fira Mono',
        'Fira Sans',
        'FontAwesome',
        'Frank Ruehl CLM',
        'Gentium Basic',
        'Gentium Book Basic',
        'Hack',
        'Heebo',
        'Helvetica',
        'Helvetica Narrow',
        'IBM Plex Mono',
        'Inconsolata',
        'Inter',
        'Iosevka',
        'JetBrains Mono',
        'Josefin Sans',
        'KacstBook',
        'KacstOffice',
        'Karla',
        'Lato',
        'Lato Black',
        'Lato Hairline',
        'Lato Heavy',
        'Lato Light',
        'Lato Medium',
        'Lato Semibold',
        'Lato Thin',
        'Liberation Mono',
        'Liberation Sans',
        'Liberation Sans Narrow',
        'Liberation Serif',
        'Linux Biolinum O',
        'Linux Libertine Display O',
        'Linux Libertine O',
        'Manrope',
        'Merriweather',
        'Meslo LG L',
        'Meslo LG M',
        'Meslo LG S',
        'Miriam CLM',
        'Miriam Mono CLM',
        'Montserrat',
        'Mukta',
        'Nimbus Mono PS',
        'Nimbus Roman',
        'Nimbus Sans',
        'Nimbus Sans Narrow',
        'Noto Color Emoji',
        'Noto Kufi Arabic',
        'Noto Looped Lao',
        'Noto Looped Lao Bold',
        'Noto Looped Lao Regular',
        'Noto Looped Thai',
        'Noto Looped Thai Bold',
        'Noto Looped Thai Regular',
        'Noto Mono',
        'Noto Music',
        'Noto Naskh Arabic',
        'Noto Nastaliq Urdu',
        'Noto Rashi Hebrew',
        'Noto Sans',
        'Noto Sans Adlam',
        'Noto Sans Adlam Unjoined',
        'Noto Sans AnatoHiero',
        'Noto Sans Anatolian Hieroglyphs',
        'Noto Sans Arabic',
        'Noto Sans Armenian',
        'Noto Sans Avestan',
        'Noto Sans Balinese',
        'Noto Sans Bamum',
        'Noto Sans Bassa Vah',
        'Noto Sans Batak',
        'Noto Sans Bengali',
        'Noto Sans Bhaiksuki',
        'Noto Sans Brahmi',
        'Noto Sans Buginese',
        'Noto Sans Buhid',
        'Noto Sans CJK HK',
        'Noto Sans CJK JP',
        'Noto Sans CJK KR',
        'Noto Sans CJK SC',
        'Noto Sans CJK TC',
        'Noto Sans CanAborig',
        'Noto Sans Canadian Aboriginal',
        'Noto Sans Carian',
        'Noto Sans CaucAlban',
        'Noto Sans Caucasian Albanian',
        'Noto Sans Chakma',
        'Noto Sans Cham',
        'Noto Sans Cherokee',
        'Noto Sans Coptic',
        'Noto Sans Cuneiform',
        'Noto Sans Cypriot',
        'Noto Sans Deseret',
        'Noto Sans Devanagari',
        'Noto Sans Display',
        'Noto Sans Duployan',
        'Noto Sans EgyptHiero',
        'Noto Sans Egyptian Hieroglyphs',
        'Noto Sans Elbasan',
        'Noto Sans Elymaic',
        'Noto Sans Ethiopic',
        'Noto Sans Georgian',
        'Noto Sans Glagolitic',
        'Noto Sans Gothic',
        'Noto Sans Grantha',
        'Noto Sans Gujarati',
        'Noto Sans Gunjala Gondi',
        'Noto Sans Gurmukhi',
        'Noto Sans Hanifi Rohingya',
        'Noto Sans Hanunoo',
        'Noto Sans Hatran',
        'Noto Sans Hebrew',
        'Noto Sans ImpAramaic',
        'Noto Sans Imperial Aramaic',
        'Noto Sans Indic Siyaq Numbers',
        'Noto Sans InsPahlavi',
        'Noto Sans InsParthi',
        'Noto Sans Inscriptional Pahlavi',
        'Noto Sans Inscriptional Parthian',
        'Noto Sans Javanese',
        'Noto Sans Kaithi',
        'Noto Sans Kannada',
        'Noto Sans Kayah Li',
        'Noto Sans Kharoshthi',
        'Noto Sans Khmer',
        'Noto Sans Khojki',
        'Noto Sans Khudawadi',
        'Noto Sans Lao',
        'Noto Sans Lepcha',
        'Noto Sans Limbu',
        'Noto Sans Linear A',
        'Noto Sans Linear B',
        'Noto Sans Lisu',
        'Noto Sans Lycian',
        'Noto Sans Lydian',
        'Noto Sans Mahajani',
        'Noto Sans Malayalam',
        'Noto Sans Mandaic',
        'Noto Sans Manichaean',
        'Noto Sans Marchen',
        'Noto Sans Masaram Gondi',
        'Noto Sans Math',
        'Noto Sans Mayan Numerals',
        'Noto Sans Medefaidrin',
        'Noto Sans Meetei Mayek',
        'Noto Sans Mende Kikakui',
        'Noto Sans Meroitic',
        'Noto Sans Miao',
        'Noto Sans Modi',
        'Noto Sans Mongolian',
        'Noto Sans Mono',
        'Noto Sans Mono CJK HK',
        'Noto Sans Mono CJK JP',
        'Noto Sans Mono CJK KR',
        'Noto Sans Mono CJK SC',
        'Noto Sans Mono CJK TC',
        'Noto Sans Mro',
        'Noto Sans Multani',
        'Noto Sans Myanmar',
        'Noto Sans NKo',
        'Noto Sans Nabataean',
        'Noto Sans New Tai Lue',
        'Noto Sans Newa',
        'Noto Sans Nushu',
        'Noto Sans Ogham',
        'Noto Sans Ol Chiki',
        'Noto Sans Old Hungarian',
        'Noto Sans Old Italic',
        'Noto Sans Old North Arabian',
        'Noto Sans Old Permic',
        'Noto Sans Old Persian',
        'Noto Sans Old Sogdian',
        'Noto Sans Old South Arabian',
        'Noto Sans Old Turkic',
        'Noto Sans OldHung',
        'Noto Sans OldNorArab',
        'Noto Sans OldSouArab',
        'Noto Sans Oriya',
        'Noto Sans Osage',
        'Noto Sans Osmanya',
        'Noto Sans Pahawh Hmong',
        'Noto Sans Palmyrene',
        'Noto Sans Pau Cin Hau',
        'Noto Sans PhagsPa',
        'Noto Sans Phoenician',
        'Noto Sans PsaPahlavi',
        'Noto Sans Psalter Pahlavi',
        'Noto Sans Rejang',
        'Noto Sans Runic',
        'Noto Sans Samaritan',
        'Noto Sans Saurashtra',
        'Noto Sans Sharada',
        'Noto Sans Shavian',
        'Noto Sans Siddham',
        'Noto Sans SignWrit',
        'Noto Sans SignWriting',
        'Noto Sans Sinhala',
        'Noto Sans Sogdian',
        'Noto Sans Sora Sompeng',
        'Noto Sans Soyombo',
        'Noto Sans Sundanese',
        'Noto Sans Syloti Nagri',
        'Noto Sans Symbols',
        'Noto Sans Symbols2',
        'Noto Sans Syriac',
        'Noto Sans Tagalog',
        'Noto Sans Tagbanwa',
        'Noto Sans Tai Le',
        'Noto Sans Tai Tham',
        'Noto Sans Tai Viet',
        'Noto Sans Takri',
        'Noto Sans Tamil',
        'Noto Sans Tamil Supplement',
        'Noto Sans Telugu',
        'Noto Sans Thaana',
        'Noto Sans Thai',
        'Noto Sans Tifinagh',
        'Noto Sans Tifinagh APT',
        'Noto Sans Tifinagh Adrar',
        'Noto Sans Tifinagh Agraw Imazighen',
        'Noto Sans Tifinagh Ahaggar',
        'Noto Sans Tifinagh Air',
        'Noto Sans Tifinagh Azawagh',
        'Noto Sans Tifinagh Ghat',
        'Noto Sans Tifinagh Hawad',
        'Noto Sans Tifinagh Rhissa Ixa',
        'Noto Sans Tifinagh SIL',
        'Noto Sans Tifinagh Tawellemmet',
        'Noto Sans Tirhuta',
        'Noto Sans Ugaritic',
        'Noto Sans Vai',
        'Noto Sans Wancho',
        'Noto Sans Warang Citi',
        'Noto Sans Yi',
        'Noto Sans Zanabazar',
        'Noto Sans Zanabazar Square',
        'Noto Serif',
        'Noto Serif Ahom',
        'Noto Serif Armenian',
        'Noto Serif Balinese',
        'Noto Serif Bengali',
        'Noto Serif CJK HK',
        'Noto Serif CJK JP',
        'Noto Serif CJK KR',
        'Noto Serif CJK SC',
        'Noto Serif CJK TC',
        'Noto Serif Devanagari',
        'Noto Serif Display',
        'Noto Serif Dogra',
        'Noto Serif Ethiopic',
        'Noto Serif Georgian',
        'Noto Serif Grantha',
        'Noto Serif Gujarati',
        'Noto Serif Gurmukhi',
        'Noto Serif Hebrew',
        'Noto Serif Hmong Nyiakeng',
        'Noto Serif Kannada',
        'Noto Serif Khmer',
        'Noto Serif Khojki',
        'Noto Serif Lao',
        'Noto Serif Malayalam',
        'Noto Serif Myanmar',
        'Noto Serif Sinhala',
        'Noto Serif Tamil',
        'Noto Serif Tamil Slanted',
        'Noto Serif Tangut',
        'Noto Serif Telugu',
        'Noto Serif Thai',
        'Noto Serif Tibetan',
        'Noto Serif Yezidi',
        'Noto Traditional Nushu',
        'Nunito',
        'Nunito Sans',
        'Open Sans',
        'OpenSymbol',
        'Oswald',
        'Overpass Mono',
        'P052',
        'PT Mono',
        'PT Sans',
        'PT Serif',
        'Palatino',
        'Palatino Linotype',
        'Playfair Display',
        'Poppins',
        'Quicksand',
        'Raleway',
        'Reem Kufi',
        'Roboto',
        'Roboto Condensed',
        'Roboto Mono',
        'Roboto Slab',
        'Rubik',
        'Scheherazade',
        'Source Code Pro',
        'Source Sans 3',
        'Source Serif 4',
        'Space Mono',
        'Standard Symbols PS',
        'Symbol',
        'Times',
        'Times New Roman',
        'Tinos',
        'Titillium Web',
        'Twemoji Mozilla',
        'URW Bookman',
        'URW Gothic',
        'Ubuntu',
        'Ubuntu Mono',
        'Ubuntu Sans',
        'Ubuntu Sans Mono',
        'Victor Mono',
        'Work Sans',
        'Z003',
        'Zapf Chancery',
    ),
}
