#!/bin/bash

# See windows/notes.rst for instructions on slimming down Qt.
# For versions of Qt < 5.6 you need to apply this patch: 
# https://codereview.qt-project.org/#/c/125923/

cd $SW/build/qt-* && \
rm -rf build && mkdir build && cd build && \
../configure -opensource -confirm-license -prefix $SW/qt  -release -nomake examples -nomake tests -no-sql-odbc -no-sql-psql -no-qml-debug -I $SW/include -L $SW/lib && \
make -j2 && rm -rf $SW/qt && make install 

