#!/bin/sh

export libusbmuxd_CFLAGS=-I$SW/include
export libusbmuxd_LIBS=-lusbmuxd
export libplist_CFLAGS=-I$SW/include
export libplist_LIBS=-lplist
export libplistmm_CFLAGS=-I$SW/include
export libplistmm_LIBS=-lplist++
export openssl_CFLAGS=-I/usr/include
export openssl_LIBS="-lcrypto -lssl"

cd $SW/build/libimobiledevice-* && ./configure --prefix=$SW --disable-dependency-tracking --without-cython --disable-static && make && make install
