#!/bin/sh

# lxml must be built with statically linked libxml2 and libxslt as python on
# OS X loads the system version of these libraries, which can cause incompatibility
# First run python setup.py install and abort it when it reaches the compiling phase

CC=gcc
BTEMP=build/temp.macosx-10.7-x86_64-2.7
BLIB=build/lib.macosx-10.7-x86_64-2.7
PYH=$SW/python/Python.framework/Versions/Current/Headers
LXML=src/lxml/includes
LIBXML=$SW/private/libxml2

cd $SW/build/lxml-3* && rm -rf build/* && \
echo Builiding extension modules... && \
mkdir -p $BTEMP/src/lxml/ $BLIB/lxml/ && \
$CC $CFLAGS -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I$LIBXML/include/libxml2 -I$LIBXML/include/libxslt -I/usr/include -I$PYH -I$LXML -c src/lxml/lxml.etree.c -o $BTEMP/src/lxml/lxml.etree.o -w  -flat_namespace && \
$CC $CFLAGS -bundle -undefined dynamic_lookup  $BTEMP/src/lxml/lxml.etree.o $LIBXML/lib/libxml2.a $LIBXML/lib/libxslt.a $LIBXML/lib/libexslt.a $SW/lib/libz.a $SW/lib/libiconv.a  -lm -o $BLIB/lxml/etree.so && \
$CC $CFLAGS -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I$LIBXML/include/libxml2 -I$LIBXML/include/libxslt -I/usr/include -I$PYH -I$LXML -c src/lxml/lxml.objectify.c -o $BTEMP/src/lxml/lxml.objectify.o -w -flat_namespace && \
$CC $CFLAGS -bundle -undefined dynamic_lookup  $BTEMP/src/lxml/lxml.objectify.o $LIBXML/lib/libxml2.a $LIBXML/lib/libxslt.a $LIBXML/lib/libexslt.a $SW/lib/libz.a $SW/lib/libiconv.a  -lm -o $BLIB/lxml/objectify.so && \
python setup.py install
