#!/bin/bash


export CFLAGS="$CFLAGS -mmacosx-version-min=10.7"
export LDFLAGS="$LDFLAGS -Wl,-headerpad_max_install_names -mmacosx-version-min=10.7"

cd $SW/build/Pillow* && \
    echo Disabling zip_safe && \
    python -c "f = open('setup.py', 'r+b'); raw = f.read(); import re; raw = re.sub(r'zip_safe\s*=\s*True', 'zip_safe=False', raw); f.seek(0); f.truncate(0); f.write(raw)" && \
    python setup.py install

