#!/bin/sh

# Edit setup.py

# Disable Tk by adding return 0 to the start of detect_tkinter_darwin

OPENSSL=$SW/private/ssl
export CFLAGS="-I$OPENSSL/include $CFLAGS -DHAVE_LOAD_EXTENSION"
export LDFLAGS="-L$OPENSSL/lib $LDFLAGS"

cd $SW/build/Python-* && \
./configure --prefix=$SW --enable-framework=$SW/python --enable-ipv6 --enable-unicode=ucs2  --with-signal-module --with-threads --with-pymalloc --with-system-expat && make -j2 && make install

# Now create a symlink from ~/sw/bin/python to the newly installed python binary so that it becomes the default python
# Install setuptools as described in windows/notes. Create symlink for ~/sw/bin/easy_install
# Use setuptools to install the various python packages
