#!/bin/sh

export LIBUSB_CFLAGS="-I$SW/include/libusb-1.0"
export LIBUSB_LIBS="-L$SW/lib -lusb-1.0"
export CFLAGS="$CFLAGS -DHAVE_ICONV"
export LDFLAGS="$LDFLAGS -liconv"

cd $SW/build/libmtp-* && \
./configure --disable-dependency-tracking --disable-static --prefix=$SW --with-libiconv-prefix=$SW && \
make && make install

