#!/bin/sh

export CMAKE_INCLUDE_PATH=$SW/include
export CMAKE_LIBRARY_PATH=$SW/lib

cd $SW/build/podofo* && \
rm -rf podofo-build && mkdir podofo-build && \
cd podofo-build && \

echo "Running cmake..." && \

# We set c++98 and libstdc++ as PoDoFo does not use C++11 and without that it
# will be compiled with C++11 and linked against libc++, which means the PoDoFo
# calibre extension would also have to be compiled and liked that way.
cmake -G "Unix Makefiles" -Wno-dev \
                -DFREETYPE_INCLUDE_DIR=$SW/include/freetype2 \
                -DFREETYPE_LIBRARIES=-lfreetype \
                -DCMAKE_BUILD_TYPE=RELEASE \
                -DPODOFO_BUILD_SHARED:BOOL=TRUE \
                -DPODOFO_BUILD_STATIC:BOOL=FALSE \
                -DCMAKE_CXX_FLAGS="${CFLAGS} -std=c++98 -stdlib=libstdc++" \
                -DCMAKE_INSTALL_PREFIX=$SW \
                .. && \
make VERBOSE=0 podofo_shared && \
rm -rf $SW/lib/libpodofo*.dylib $SW/include/podofo && \
mkdir $SW/include/podofo && \
cp src/libpodofo.*.dylib $SW/lib && \
cp -r podofo_config.h ../src/* $SW/include/podofo/ && \
cd $SW/lib/ && install_name_tool -id $SW/lib/libpodofo* $SW/lib/libpodofo.* && ln -s libpodofo*.dylib libpodofo.dylib
