#!/bin/sh

# Edit makefile.unix setting the vars as shown

CXX=g++
CXXFLAGS=-O2 -arch x86_64 -dynamic
DEFINES=-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_SILENT -DSILENT
STRIP=strip
DESTDIR=$SW
WHAT=RARDLL

cd $SW/unrar && make -fmakefile.unic lib && cp libunrar.so $SW/lib/libunrar.dylib
