# autogenerated by __main__.py do not edit
import PyQt6.QtDBus
QDBus = PyQt6.QtDBus.QDBus
QDBusAbstractAdaptor = PyQt6.QtDBus.QDBusAbstractAdaptor
QDBusAbstractInterface = PyQt6.QtDBus.QDBusAbstractInterface
QDBusArgument = PyQt6.QtDBus.QDBusArgument
QDBusConnection = PyQt6.QtDBus.QDBusConnection
QDBusConnectionInterface = PyQt6.QtDBus.QDBusConnectionInterface
QDBusError = PyQt6.QtDBus.QDBusError
QDBusInterface = PyQt6.QtDBus.QDBusInterface
QDBusMessage = PyQt6.QtDBus.QDBusMessage
QDBusObjectPath = PyQt6.QtDBus.QDBusObjectPath
QDBusPendingCall = PyQt6.QtDBus.QDBusPendingCall
QDBusPendingCallWatcher = PyQt6.QtDBus.QDBusPendingCallWatcher
QDBusPendingReply = PyQt6.QtDBus.QDBusPendingReply
QDBusReply = PyQt6.QtDBus.QDBusReply
QDBusServiceWatcher = PyQt6.QtDBus.QDBusServiceWatcher
QDBusSignature = PyQt6.QtDBus.QDBusSignature
QDBusUnixFileDescriptor = PyQt6.QtDBus.QDBusUnixFileDescriptor
QDBusVariant = PyQt6.QtDBus.QDBusVariant