#!/usr/bin/env python3

import sys
import subprocess
import re
import os

refname = sys.argv[1]
oldname = sys.argv[2]
newname = sys.argv[3]
print("TEST")
print(refname)
print(newname)
print(oldname)

all_lines = subprocess.run(["git", "log", f"{newname}"], stdout=subprocess.PIPE).stdout.decode('utf-8')

index = 0

for line in all_lines.splitlines():
	if "commit" in line:
		if oldname in line:
			print("valid ref")

			break

		message = all_lines.splitlines()[index + 4].strip()

		assert message[-1] == "]"


		assert re.search(r"\[[A-Z]{4}-[0-9]{4}\]", message)

		files = subprocess.run(["git", "diff-tree", "--name-only", f"{newname}"], stdout=subprocess.PIPE).stdout.decode('utf-8').splitlines()[1:]

		for file in files:
			if file == "main.c" or file == "secrets":
				# if not os.path.exists('tmp/sensitive.log'):
				# 	os.mknod('/tmp')
				f = open("/tmp/sensitive.log", "a")

				f.write(f"{line},{all_lines.splitlines()[index + 1]}")
				f.write("\n")

	index += 1