#!/bin/bash
if [[ `uname -m` == "i686" ]]; then
openssltarget=linux-elf;
optflags=''
else
openssltarget=linux-x86_64;
optflags='enable-ec_nistp_64_gcc_128';
fi

cd $SW/build/openssl-* && \
    ./Configure --prefix=/usr --openssldir=/etc/ssl shared zlib $optflags $openssltarget -Wa,--noexecstack $CFLAGS $LDFLAGS && make && make test && \
    rm -rf $SW/openssl && rm -rf $SW/include/openssl && rm -f $SW/lib/libcrypto* $SW/lib/libssl* && \
    make INSTALL_PREFIX=$SW/openssl install_sw && cp -ra $SW/openssl/usr/include/openssl $SW/include/ && cp -a $SW/openssl/usr/lib/lib*.so* $SW/lib && \
    rm -rf $SW/openssl
