#!/bin/bash

export CXXFLAGS="$CFLAGS"
export FONTCONFIG_CFLAGS="-I$SW/include/fontconfig -I$SW/include"
export FONTCONFIG_LIBS="-L$SW/lib -lfontconfig"
export FREETYPE_CFLAGS="-I$SW/include/freetype2 -I$SW/include"
export FREETYPE_LIBS="-L$SW/lib -lfreetype -lz"
export FREETYPE_CONFIG="$SW/bin/freetype-config"
export LIBJPEG_LIBS="-L$SW/lib -ljpeg"
export LIBPNG_LIBS="-L$SW/lib -lpng"
export LIBPNG_CFLAGS="-I$SW/include/libpng16"

cd $SW/build/poppler* && \
./configure --prefix $SW --without-x --enable-shared --disable-dependency-tracking  --disable-silent-rules --enable-zlib --enable-splash-output --disable-cairo-output --disable-poppler-glib  --disable-poppler-qt4 --disable-poppler-qt5 --disable-poppler-cpp --disable-gtk-test  --enable-libjpeg --enable-compile-warnings=no && make V=1 && make install 

