#!/bin/sh

export CFLAGS="$CFLAGS -DHAVE_LOAD_EXTENSION"

# Needed otherwise _ssl module fails to import because system openssl is too old
export LD_LIBRARY_PATH=$SW/lib

cd $SW/build/Python-* && \
./configure --prefix=$SW --enable-ipv6 --enable-unicode=ucs4 --with-signal-module --with-threads --with-pymalloc --with-system-expat --enable-shared && make -j2 && make install

# Install setuptools as described in windows/notes. 
# Use setuptools to install the various python packages
