#!/bin/sh

# Apply the patch to prevent detection of WIFI devices, from http://www.mobileread.com/forums/showthread.php?t=255234

export libplist_CFLAGS="-I$SW/include"
export libplist_LIBS="-L$SW/lib -lplist"
export CPPFLAGS="$CFLAGS"
export CXXFLAGS="$CFLAGS"

cd $SW/build/libusbmuxd-* && \
    ./configure --prefix=$SW --disable-dependency-tracking && \
    make && make install
