#!/bin/sh

export CMAKE_INCLUDE_PATH=$SW/include
export CMAKE_LIBRARY_PATH=$SW/lib

cd $SW/build/podofo* && \
rm -rf $SW/include/podofo && \
rm -rf podofo-build && mkdir podofo-build && \
cd podofo-build && \

echo "Running cmake..." && \

cmake -G "Unix Makefiles" -Wno-dev \
                -DFREETYPE_INCLUDE_DIR=$SW/include/freetype2 \
                -DFREETYPE_LIBRARIES=-lfreetype \
                -DCMAKE_BUILD_TYPE=RELEASE \
                -DPODOFO_BUILD_SHARED:BOOL=TRUE \
                -DPODOFO_BUILD_STATIC:BOOL=FALSE \
                -DCMAKE_INSTALL_PREFIX=$SW \
                .. && \
make VERBOSE=0 podofo_shared && \
rm -rf $SW/lib/libpodofo* $SW/include/podofo && \
mkdir $SW/include/podofo && \
cp src/libpodofo* $SW/lib && \
cp -r podofo_config.h ../src/* $SW/include/podofo/ 
