#!/usr/bin/env python
# License: GPLv3 Copyright: 2026, Kovid Goyal <kovid at kovidgoyal.net>

import hashlib
import json
import os

from setup.revendor import ReVendor

# The revisions of the model and dictionaries to use. Change these and run
# ./setup.py kokoro_voices to update.
MODEL_REPO = 'onnx-community/Kokoro-82M-v1.0-ONNX'
MODEL_REVISION = '1939ad2a8e416c0acfeecc08a694d14ef25f2231'
MODEL_FILE = 'onnx/model.onnx'
MISAKI_REVISION = 'fba1236595f2d2bf21d414ba6e57d25256afada3'

# Kokoro language code to language metadata. Japanese and Mandarin are not
# supported as the model was trained on phonemes generated by tools other
# than espeak-ng for them.
LANGUAGES = {
    'a': {'lang': 'en', 'country': 'US', 'espeak': 'en-us', 'lexicon': 'us'},
    'b': {'lang': 'en', 'country': 'GB', 'espeak': 'en', 'lexicon': 'gb'},
    'e': {'lang': 'es', 'country': '', 'espeak': 'es', 'lexicon': ''},
    'f': {'lang': 'fr', 'country': 'FR', 'espeak': 'fr', 'lexicon': ''},
    'h': {'lang': 'hi', 'country': 'IN', 'espeak': 'hi', 'lexicon': ''},
    'i': {'lang': 'it', 'country': 'IT', 'espeak': 'it', 'lexicon': ''},
    'p': {'lang': 'pt', 'country': 'BR', 'espeak': 'pt-br', 'lexicon': ''},
}

# Languages for which a Kokoro voice is used by default, ISO 639-2 code to voice id
DEFAULT_VOICES = {'eng': 'af_heart'}

# Overall quality grades from https://huggingface.co/hexgrad/Kokoro-82M/blob/main/VOICES.md
GRADES = {
    'af_heart': 'A',
    'af_alloy': 'C',
    'af_aoede': 'C+',
    'af_bella': 'A-',
    'af_jessica': 'D',
    'af_kore': 'C+',
    'af_nicole': 'B-',
    'af_nova': 'C',
    'af_river': 'D',
    'af_sarah': 'C+',
    'af_sky': 'C-',
    'am_adam': 'F+',
    'am_echo': 'D',
    'am_eric': 'D',
    'am_fenrir': 'C+',
    'am_liam': 'D',
    'am_michael': 'C+',
    'am_onyx': 'D',
    'am_puck': 'C+',
    'am_santa': 'D-',
    'bf_alice': 'D',
    'bf_emma': 'B-',
    'bf_isabella': 'C',
    'bf_lily': 'D',
    'bm_daniel': 'D',
    'bm_fable': 'C',
    'bm_george': 'C',
    'bm_lewis': 'D+',
    'ff_siwis': 'B-',
    'hf_alpha': 'C',
    'hf_beta': 'C',
    'hm_omega': 'C',
    'hm_psi': 'C',
    'if_sara': 'C',
    'im_nicola': 'C',
}


class KokoroVoices(ReVendor):
    description = 'Generate the list of Kokoro voices with pinned download URLs and hashes'
    NAME = 'kokoro_voices'
    TAR_NAME = 'kokoro voice list'
    VERSION = MODEL_REVISION
    DOWNLOAD_URL = f'https://huggingface.co/api/models/{MODEL_REPO}/tree/{MODEL_REVISION}'
    CAN_USE_SYSTEM_VERSION = False

    @property
    def output_file_path(self) -> str:
        return os.path.join(self.RESOURCES, 'kokoro-voices.json')

    def hf_url(self, path: str) -> str:
        return f'https://huggingface.co/{MODEL_REPO}/resolve/{MODEL_REVISION}/{path}'

    def hf_tree(self, path: str) -> dict[str, dict[str, object]]:
        url = f'{self.DOWNLOAD_URL}/{path}' if path else self.DOWNLOAD_URL
        items: list[dict[str, object]] = json.loads(self.download_securely(url))
        return {str(x['path']): x for x in items}

    def file_data_from_tree(self, entry: dict[str, object]) -> dict[str, object]:
        lfs = entry.get('lfs')
        if not isinstance(lfs, dict) or not lfs.get('oid'):
            raise SystemExit(f'{entry["path"]} is not stored in LFS so its hash is unknown')
        return {'url': self.hf_url(str(entry['path'])), 'sha256': lfs['oid'], 'size': int(str(lfs['size']))}

    def file_data_from_download(self, url: str) -> dict[str, object]:
        self.info('Downloading', url)
        data = self.download_securely(url)
        return {'url': url, 'sha256': hashlib.sha256(data).hexdigest(), 'size': len(data)}

    def run(self, opts):
        model_tree = self.hf_tree('onnx')
        if MODEL_FILE not in model_tree:
            raise SystemExit(f'{MODEL_FILE} not found in {MODEL_REPO}')
        tokenizer = json.loads(self.download_securely(self.hf_url('tokenizer.json')))
        vocab: dict[str, int] = tokenizer['model']['vocab']
        if not vocab:
            raise SystemExit('No vocabulary found in tokenizer.json')
        voices = {}
        for path, entry in self.hf_tree('voices').items():
            voice_id = os.path.basename(path).rpartition('.')[0]
            lang_code, sep, name = voice_id.partition('_')
            if not sep or len(lang_code) != 2 or lang_code[0] not in LANGUAGES or lang_code[1] not in 'fm':
                continue
            voices[voice_id] = {
                'name': name.capitalize(),
                'lang': lang_code[0],
                'gender': lang_code[1],
                'grade': GRADES.get(voice_id, ''),
                **self.file_data_from_tree(entry),
            }
        for v in DEFAULT_VOICES.values():
            if v not in voices:
                raise SystemExit(f'The default voice {v} was not found')
        lexicons = {}
        for lexicon in {x['lexicon'] for x in LANGUAGES.values() if x['lexicon']}:
            lexicons[lexicon] = {
                q: self.file_data_from_download(f'https://raw.githubusercontent.com/hexgrad/misaki/{MISAKI_REVISION}/misaki/data/{lexicon}_{q}.json')
                for q in ('gold', 'silver')
            }
        data = {
            'version': 1,
            'sample_rate': 24000,
            'model': self.file_data_from_tree(model_tree[MODEL_FILE]),
            'vocab': vocab,
            'lexicons': lexicons,
            'languages': LANGUAGES,
            'default_voices': DEFAULT_VOICES,
            'voices': dict(sorted(voices.items())),
        }
        with open(self.output_file_path, 'w') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
            f.write('\n')
        self.info(f'Wrote {len(voices)} voices to {self.output_file_path}')

    def clean(self):
        # The output is checked into the repository, so it is not removed
        pass
