/*
 * avif_plugin.h
 * Copyright (C) 2026 Kovid Goyal <kovid at kovidgoyal.net>
 *
 * Distributed under terms of the GPL3 license.
 */

#pragma once

// The plugin below is built as a static Qt plugin and registered with Qt when
// the calibre_extensions.avif module is imported. This must be defined before
// any Qt headers are included as qplugin.h uses it to decide how the plugin
// metadata generated by moc is exported.
#ifndef QT_STATICPLUGIN
#define QT_STATICPLUGIN
#endif

#include <QByteArray>
#include <QImageIOPlugin>

struct avifDecoder;

class AvifHandler : public QImageIOHandler {
  public:
    AvifHandler();
    ~AvifHandler() override;

    // Returns true if the next bytes in device look like the start of an AVIF file
    static bool can_read_from(QIODevice *device);

    bool canRead() const override;
    bool read(QImage *image) override;

    QVariant option(ImageOption option) const override;
    bool supportsOption(ImageOption option) const override;

    int imageCount() const override;
    int currentImageNumber() const override;
    bool jumpToImage(int image_number) override;
    bool jumpToNextImage() override;
    int nextImageDelay() const override;
    int loopCount() const override;

  private:
    // Read the entire stream and parse the AVIF container, idempotent
    bool parse() const;

    mutable avifDecoder *decoder;
    mutable QByteArray raw;
    mutable bool parse_failed;
    int next_frame;
};

class AvifPlugin : public QImageIOPlugin {
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QImageIOHandlerFactoryInterface_iid FILE "avif.json")

  public:
    Capabilities capabilities(QIODevice *device, const QByteArray &format) const override;
    QImageIOHandler *create(QIODevice *device, const QByteArray &format = QByteArray()) const override;
};

// The AVIF image format is registered with Qt when this shared object is
// loaded. Returns true if QImageReader can read AVIF images, i.e. if that
// registration worked.
bool register_avif_image_format();

// Returns true if data is the start of a file in a container format libavif can read
bool is_avif(const char *data, size_t len);
