name: TESTSKIP
on: [push, pull_request]
permissions:
    contents: read # to fetch code (actions/checkout)

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}

    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        base: ${{ github.ref }}
        filters: |
          src:
            - '!**/*.md'
  test:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ needs.changes.outputs.src }}